import { Pressable, StyleSheet, View } from "react-native";
import type { ReactNode } from "react";
import { T as Text, TI as TextInput } from "@/components/typography";
import { ON_GREEN, S, type Palette, withAlpha } from "@/theme";
import { useTheme } from "@/lib/theme-context";

export interface EventTierDraft { name: string; priceGhs: string; capacity: string }
export interface EventDetailsDraft {
  format: string; audience: string[]; admission: "free" | "paid"; organiser: string; contactInfo: string;
  startTime: string; endTime: string; highlights: string; featuredGuests: string; ageGuidance: string;
  accessibility: string; dressCode: string; refundPolicy: string; tiers: EventTierDraft[];
}
export const EMPTY_EVENT_DETAILS: EventDetailsDraft = { format: "community", audience: ["all-ages"], admission: "free", organiser: "", contactInfo: "", startTime: "", endTime: "", highlights: "", featuredGuests: "", ageGuidance: "", accessibility: "", dressCode: "", refundPolicy: "", tiers: [] };

const FORMATS = [{ id: "festival", label: "Festival", mark: "✦" }, { id: "concert", label: "Concert", mark: "♫" }, { id: "workshop", label: "Workshop", mark: "✎" }, { id: "conference", label: "Conference", mark: "▦" }, { id: "community", label: "Community", mark: "◎" }, { id: "sports", label: "Sports", mark: "◉" }, { id: "ceremony", label: "Ceremony", mark: "♜" }, { id: "exhibition", label: "Exhibition", mark: "◇" }, { id: "nightlife", label: "Nightlife", mark: "☾" }, { id: "fundraiser", label: "Fundraiser", mark: "♡" }];
const AUDIENCES = [{ id: "all-ages", label: "All ages", mark: "◎" }, { id: "families", label: "Families", mark: "⌂" }, { id: "adults", label: "Adults", mark: "18" }, { id: "children", label: "Children", mark: "☆" }, { id: "students", label: "Students", mark: "⌑" }, { id: "professionals", label: "Professionals", mark: "▣" }];

export function EventDetailsFields({ value, onChange }: Readonly<{ value: EventDetailsDraft; onChange: (value: EventDetailsDraft) => void }>) {
  const { C } = useTheme(); const s = styles(C); const set = <K extends keyof EventDetailsDraft>(key: K, next: EventDetailsDraft[K]) => onChange({ ...value, [key]: next });
  const toggleAudience = (id: string) => set("audience", value.audience.includes(id) ? value.audience.filter((item) => item !== id) : [...value.audience, id]);
  const updateTier = (index: number, patch: Partial<EventTierDraft>) => set("tiers", value.tiers.map((tier, i) => i === index ? { ...tier, ...patch } : tier));
  return <View style={s.wrap}>
    <Text style={s.kicker}>EVENT EXPERIENCE</Text><Text style={s.title}>Help people know what to expect</Text><Text style={s.body}>Add the format, audience, highlights, guests and practical arrival information.</Text>
    <Text style={s.label}>EVENT FORMAT</Text><View style={s.grid}>{FORMATS.map((item) => <Option key={item.id} label={item.label} mark={item.mark} active={value.format === item.id} onPress={() => set("format", item.id)} styles={s} />)}</View>
    <Text style={s.label}>WHO IS IT FOR?</Text><Text style={s.help}>Select every audience that is welcome.</Text><View style={s.grid}>{AUDIENCES.map((item) => <Option key={item.id} label={item.label} mark={item.mark} active={value.audience.includes(item.id)} onPress={() => toggleAudience(item.id)} styles={s} />)}</View>
    <Row><Field label="START TIME"><TextInput style={s.input} value={value.startTime} onChangeText={(v) => set("startTime", v)} placeholder="e.g. 14:00" placeholderTextColor={C.inkFaint} /></Field><Field label="END TIME"><TextInput style={s.input} value={value.endTime} onChangeText={(v) => set("endTime", v)} placeholder="e.g. 20:00" placeholderTextColor={C.inkFaint} /></Field></Row>
    <Text style={s.label}>ORGANISER</Text><TextInput style={s.input} value={value.organiser} onChangeText={(v) => set("organiser", v)} placeholder="Organisation or host name" placeholderTextColor={C.inkFaint} />
    <Text style={s.label}>CONTACT FOR QUESTIONS</Text><TextInput style={s.input} value={value.contactInfo} onChangeText={(v) => set("contactInfo", v)} placeholder="Phone, email or WhatsApp" placeholderTextColor={C.inkFaint} />
    <Text style={s.label}>EVENT HIGHLIGHTS · ONE PER LINE</Text><TextInput style={[s.input, s.area]} value={value.highlights} onChangeText={(v) => set("highlights", v)} multiline placeholder={"Live performances\nFood village\nChildren’s activities"} placeholderTextColor={C.inkFaint} />
    <Text style={s.label}>FEATURED GUESTS / PERFORMERS · ONE PER LINE</Text><TextInput style={[s.input, s.area]} value={value.featuredGuests} onChangeText={(v) => set("featuredGuests", v)} multiline placeholder="Confirmed name — role or act" placeholderTextColor={C.inkFaint} />
    <Text style={s.label}>AGE GUIDANCE</Text><TextInput style={s.input} value={value.ageGuidance} onChangeText={(v) => set("ageGuidance", v)} placeholder="All ages, 18+, children with guardian…" placeholderTextColor={C.inkFaint} />
    <Text style={s.label}>DRESS CODE (OPTIONAL)</Text><TextInput style={s.input} value={value.dressCode} onChangeText={(v) => set("dressCode", v)} placeholder="Casual, traditional wear, formal…" placeholderTextColor={C.inkFaint} />
    <Text style={s.label}>ACCESSIBILITY AND ARRIVAL</Text><TextInput style={[s.input, s.area]} value={value.accessibility} onChangeText={(v) => set("accessibility", v)} multiline placeholder="Accessible entrance, seating, parking, transport…" placeholderTextColor={C.inkFaint} />
    <Text style={s.label}>ADMISSION</Text><View style={s.grid}><Option label="Free entry" mark="0" active={value.admission === "free"} onPress={() => set("admission", "free")} styles={s} /><Option label="Paid tickets" mark="₵" active={value.admission === "paid"} onPress={() => set("admission", "paid")} styles={s} /></View>
    {value.admission === "paid" ? <View><Text style={s.label}>TICKET TYPES</Text><Text style={s.help}>Capacity left empty or zero means unlimited.</Text>{value.tiers.map((tier, index) => <View key={`tier-${index}`} style={s.tier}><TextInput style={s.input} value={tier.name} onChangeText={(v) => updateTier(index, { name: v })} placeholder="Ticket name — General, VIP…" placeholderTextColor={C.inkFaint} /><Row><TextInput style={[s.input, s.flex]} value={tier.priceGhs} onChangeText={(v) => updateTier(index, { priceGhs: v })} keyboardType="decimal-pad" placeholder="Price GH₵" placeholderTextColor={C.inkFaint} /><TextInput style={[s.input, s.flex]} value={tier.capacity} onChangeText={(v) => updateTier(index, { capacity: v })} keyboardType="number-pad" placeholder="Capacity" placeholderTextColor={C.inkFaint} /></Row><Pressable accessibilityRole="button" onPress={() => set("tiers", value.tiers.filter((_, i) => i !== index))} style={s.remove}><Text style={s.removeText}>Remove ticket type</Text></Pressable></View>)}<Pressable accessibilityRole="button" disabled={value.tiers.length >= 8} onPress={() => set("tiers", [...value.tiers, { name: "", priceGhs: "", capacity: "" }])} style={s.add}><Text style={s.addText}>+ Add ticket type</Text></Pressable></View> : null}
    <Text style={s.label}>REFUND OR CANCELLATION POLICY</Text><TextInput style={[s.input, s.area]} value={value.refundPolicy} onChangeText={(v) => set("refundPolicy", v)} multiline placeholderTextColor={C.inkFaint} />
  </View>;
}

function Option({ label, mark, active, onPress, styles: s }: Readonly<{ label: string; mark: string; active: boolean; onPress: () => void; styles: ReturnType<typeof styles> }>) { return <Pressable accessibilityRole="button" accessibilityState={{ selected: active }} onPress={onPress} style={[s.option, active && s.optionOn]}><Text style={[s.optionText, active && s.optionTextOn]}>{label}</Text><Text style={s.watermark}>{mark}</Text>{active ? <View style={s.check}><Text style={s.tick}>✓</Text></View> : null}</Pressable>; }
function Field({ label, children }: Readonly<{ label: string; children: ReactNode }>) { const { C } = useTheme(); const s = styles(C); return <View style={s.flex}><Text style={s.label}>{label}</Text>{children}</View>; }
function Row({ children }: Readonly<{ children: ReactNode }>) { return <View style={{ flexDirection: "row", gap: 8 }}>{children}</View>; }
const styles = (C: Palette) => StyleSheet.create({ wrap: { marginTop: 14, borderWidth: 1, borderColor: C.goldBorder35, borderRadius: 16, backgroundColor: C.goldTint14, padding: 14 }, kicker: { color: C.goldText, fontSize: 10, letterSpacing: 1.5, ...S(700) }, title: { color: C.ink, fontSize: 21, lineHeight: 27, ...S(700), marginTop: 5 }, body: { color: C.inkMuted, fontSize: 12.5, lineHeight: 19, marginTop: 5 }, label: { color: C.ink, fontSize: 11, letterSpacing: 1.1, ...S(700), marginTop: 17, marginBottom: 7 }, help: { color: C.inkFaint, fontSize: 11, lineHeight: 16 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 }, option: { width: "48.5%", minHeight: 64, overflow: "hidden", justifyContent: "center", borderWidth: 1, borderColor: C.sand, borderRadius: 12, backgroundColor: C.paper, padding: 12, paddingRight: 34 }, optionOn: { borderColor: C.green, backgroundColor: withAlpha(C.green, 0.07) }, optionText: { color: C.inkMuted, fontSize: 13, ...S(600), zIndex: 1 }, optionTextOn: { color: C.greenText }, watermark: { position: "absolute", right: 2, bottom: -13, color: C.ink, opacity: 0.06, fontSize: 50, ...S(700) }, check: { position: "absolute", right: 8, top: 8, width: 20, height: 20, borderRadius: 10, backgroundColor: C.green, alignItems: "center", justifyContent: "center" }, tick: { color: ON_GREEN, fontSize: 10, ...S(700) }, input: { minHeight: 48, borderWidth: 1, borderColor: C.sand, borderRadius: 12, backgroundColor: C.paper, color: C.ink, paddingHorizontal: 13, paddingVertical: 11, fontSize: 14 }, area: { minHeight: 100, textAlignVertical: "top" }, flex: { flex: 1 }, tier: { gap: 8, borderWidth: 1, borderColor: C.sand, borderRadius: 12, backgroundColor: C.paper, padding: 10, marginTop: 10 }, remove: { alignSelf: "flex-start", borderWidth: 1, borderColor: withAlpha(C.maroon, 0.25), borderRadius: 8, paddingHorizontal: 11, paddingVertical: 8 }, removeText: { color: C.maroonText, fontSize: 11, ...S(700) }, add: { marginTop: 10, borderWidth: 2, borderStyle: "dashed", borderColor: C.sand, borderRadius: 12, padding: 12, alignItems: "center" }, addText: { color: C.greenText, fontSize: 12, ...S(700) } });
