import { useState } from "react";
import { useLoaderData } from "react-router-dom";
import { api } from "@/lib/api";
import type { AffiliateConversion, AffiliateProgramme, BusinessVerification, CommerceOrder, CommercePromotion } from "@/lib/types";
import { PageHeader, Pill } from "@/components/ui";

export async function loader() { const [verifications, orders, promotions, programmes, conversions] = await Promise.all([api.businessVerifications(), api.commerceOrders(),api.commercePromotions(),api.affiliateProgrammes(),api.affiliateConversions()]); return { verifications, orders, promotions, programmes, conversions }; }
const cedis = (n: number) => `GH₵ ${(n / 100).toLocaleString("en-GH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
export function Component() {
  const initial = useLoaderData() as { verifications: BusinessVerification[]; orders: CommerceOrder[]; promotions:CommercePromotion[]; programmes:AffiliateProgramme[]; conversions:AffiliateConversion[] };
  const [verifications, setVerifications] = useState(initial.verifications); const [busy, setBusy] = useState("");
  const [promotions,setPromotions]=useState(initial.promotions);const [promo,setPromo]=useState<CommercePromotion>({code:"",title:"",discountType:"percent",discountValue:5,active:true});const [programmes,setProgrammes]=useState(initial.programmes);const [programme,setProgramme]=useState<AffiliateProgramme>({name:"Oguaa ambassadors",commissionBps:500,fundingSource:"platform",holdDays:14,active:true});
  async function decide(v: BusinessVerification, status: "verified" | "rejected" | "revoked") { const note = status === "verified" ? "Identity, registration and settlement evidence reviewed." : window.prompt("Reviewer note") ?? ""; if (status !== "verified" && !note) return; setBusy(v.listingId); try { const next = await api.reviewBusinessVerification(v.listingId, status, note); setVerifications((rows) => rows.map((x) => x.listingId === v.listingId ? next : x)); } finally { setBusy(""); } }
  const gross = initial.orders.filter((o) => o.status !== "pending").reduce((n, o) => n + o.amountPesewas, 0); const fees = initial.orders.filter((o) => o.status !== "pending").reduce((n, o) => n + o.platformFeePesewas, 0);
  return <><PageHeader kicker="Marketplace operations" title="Business commerce" /><div className="grid gap-4 sm:grid-cols-3"><Metric label="Confirmed GMV" value={cedis(gross)} /><Metric label="Platform fees" value={cedis(fees)} /><Metric label="Orders" value={String(initial.orders.length)} /></div>
    <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-sand bg-cream p-5"><h2 className="text-2xl font-semibold">Oguaa promotions</h2><p className="mt-2 text-sm text-ink-muted">Platform-funded discounts reduce Oguaa's fee, never the business settlement.</p><div className="mt-4 grid gap-2"><input aria-label="Promotion title" placeholder="Cape Coast weekend" value={promo.title} onChange={(e)=>setPromo({...promo,title:e.target.value})} className="rounded-lg border border-sand p-2"/><input aria-label="Promotion code" placeholder="OGUAA5" value={promo.code} onChange={(e)=>setPromo({...promo,code:e.target.value.toUpperCase()})} className="rounded-lg border border-sand p-2"/><input aria-label="Discount value" type="number" value={promo.discountValue} onChange={(e)=>setPromo({...promo,discountValue:Number(e.target.value)})} className="rounded-lg border border-sand p-2"/></div><button type="button" onClick={async()=>{const saved=await api.saveCommercePromotion(promo);setPromotions((r)=>[saved,...r]);setPromo({...promo,code:"",title:""})}} className="mt-3 rounded-full bg-green px-4 py-2 text-sm font-semibold text-on-green">Launch promotion</button><div className="mt-4 text-sm">{promotions.filter((p)=>p.ownerType==="platform").map((p)=><p key={p.id}>{p.code} · {p.discountValue}{p.discountType==="percent"?"%":" pesewas"} · {p.redemptions??0} uses</p>)}</div></div><div className="rounded-2xl border border-sand bg-cream p-5"><h2 className="text-2xl font-semibold">Oguaa affiliate programme</h2><div className="mt-4 grid gap-2"><input aria-label="Programme name" value={programme.name} onChange={(e)=>setProgramme({...programme,name:e.target.value})} className="rounded-lg border border-sand p-2"/><input aria-label="Commission percent" type="number" value={programme.commissionBps/100} onChange={(e)=>setProgramme({...programme,commissionBps:Number(e.target.value)*100})} className="rounded-lg border border-sand p-2"/></div><button type="button" onClick={async()=>{const saved=await api.saveAffiliateProgramme(programme);setProgrammes((r)=>[saved,...r])}} className="mt-3 rounded-full bg-teal px-4 py-2 text-sm font-semibold text-white">Save programme</button><p className="mt-4 text-sm text-ink-muted">{programmes.length} programmes · {initial.conversions.length} attributed orders</p>{initial.conversions.map((c)=><div key={c.id} className="mt-2 flex items-center justify-between text-sm"><span>{c.affiliateCode} · {cedis(c.commissionPesewas)} · {c.status}</span>{c.status==="converted"&&<button type="button" onClick={()=>api.setAffiliateConversionStatus(c.id,"payable")} className="font-semibold text-teal-text">Release</button>}</div>)}</div></section>
    <section className="mt-8"><h2 className="text-2xl font-semibold">Verification queue</h2><div className="mt-4 grid gap-4">{verifications.map((v) => <article key={v.id} className="rounded-2xl border border-sand bg-cream p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-semibold">{v.legalName}</h3><p className="mt-1 text-sm text-ink-muted">{v.registrationNumber} · {v.ghanaPostGPS} · {v.businessPhone}</p></div><Pill tone={v.status === "verified" ? "green" : "neutral"}>{v.status}</Pill></div><dl className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-ink-faint">Ghana Card</dt><dd>{v.ghanaCardNumber}</dd></div><div><dt className="text-ink-faint">Settlement</dt><dd>{v.settlementName} · {v.settlementBankCode} · •••{v.settlementAccountNo.slice(-4)}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2">{v.documents.map((doc, i) => <a key={doc} href={doc} target="_blank" rel="noreferrer" className="text-sm font-semibold text-teal-text">Document {i + 1} ↗</a>)}</div><div className="mt-5 flex gap-2"><button disabled={busy === v.listingId} onClick={() => decide(v, "verified")} className="rounded-full bg-green px-4 py-2 text-sm font-semibold text-on-green">Verify &amp; provision subaccount</button><button disabled={busy === v.listingId} onClick={() => decide(v, "rejected")} className="rounded-full border border-clay px-4 py-2 text-sm font-semibold text-clay-text">Reject</button>{v.status === "verified" && <button onClick={() => decide(v, "revoked")} className="rounded-full border border-maroon-text px-4 py-2 text-sm font-semibold text-maroon-text">Revoke</button>}</div></article>)}</div></section>
    <section className="mt-10"><h2 className="text-2xl font-semibold">Recent orders</h2><div className="mt-4 overflow-x-auto rounded-2xl border border-sand"><table className="w-full text-left text-sm"><thead className="bg-sand/60"><tr><th className="p-3">Reference</th><th className="p-3">Business</th><th className="p-3">Buyer</th><th className="p-3">Gross</th><th className="p-3">Oguaa fee</th><th className="p-3">Business net</th><th className="p-3">Status</th></tr></thead><tbody>{initial.orders.map((o) => <tr key={o.id} className="border-t border-sand"><td className="p-3 font-medium">{o.reference}</td><td className="p-3">{o.businessName}</td><td className="p-3">{o.buyerName}</td><td className="p-3">{cedis(o.amountPesewas)}</td><td className="p-3">{cedis(o.platformFeePesewas)}</td><td className="p-3">{cedis(o.businessNetPesewas)}</td><td className="p-3">{o.status}</td></tr>)}</tbody></table></div></section></>;
}
function Metric({ label, value }: Readonly<{ label: string; value: string }>) { return <div className="rounded-2xl border border-sand bg-cream p-5"><p className="text-xs font-semibold uppercase tracking-wider text-ink-faint">{label}</p><p className="mt-2 text-2xl font-semibold text-green-text">{value}</p></div>; }
