// GENERATED by scripts/sync-legal.mjs from docs/legal/*.md — do not edit by hand.
// Edit the Markdown source, then run `node scripts/sync-legal.mjs`. CI runs it
// with --check and fails when this file is stale.

export type LegalDocKey = "privacy" | "terms" | "acceptable-use" | "terms-of-sale" | "child-safety" | "safeguarding";

/** A run of text: plain, bold, or a link (a site path, https:// URL or mailto:). */
export interface LegalInline {
  readonly text: string;
  readonly bold?: boolean;
  readonly href?: string;
}

export type LegalBlock =
  | { readonly kind: "p"; readonly parts: readonly LegalInline[] }
  | { readonly kind: "h3"; readonly text: string }
  | { readonly kind: "ul" | "ol"; readonly items: readonly (readonly LegalInline[])[] };

export interface LegalSection {
  readonly heading: string;
  readonly blocks: readonly LegalBlock[];
}

export interface LegalDoc {
  readonly key: LegalDocKey;
  readonly title: string;
  readonly kicker: string;
  readonly lede: string;
  /** Version of the text (YYYY-MM-DD). */
  readonly version: string;
  /** Date the text takes effect (YYYY-MM-DD) and its long form. */
  readonly effective: string;
  readonly effectiveLabel: string;
  readonly intro: readonly LegalBlock[];
  readonly sections: readonly LegalSection[];
}

/** Display order of the legal documents. */
export const LEGAL_DOC_KEYS: readonly LegalDocKey[] = [
  "privacy",
  "terms",
  "acceptable-use",
  "terms-of-sale",
  "child-safety",
  "safeguarding"
];

/** Current Terms of Use and Privacy Notice versions (the consent record's versions). */
export const LEGAL_TERMS_VERSION = "2026-10-01";
export const LEGAL_PRIVACY_VERSION = "2026-10-01";

/** The public web portal, where every legal document is published. */
export const LEGAL_PORTAL_ORIGIN = "https://citizen.oguaaman.com";

/** The site path of each legal document on the portal. */
export const legalPath = (key: LegalDocKey): string => `/${key}`;

/** The legal document a site path points at, if any ("/terms" → "terms"). */
export function legalDocKeyForPath(path: string): LegalDocKey | undefined {
  const key = path.replace(/^\//, "").replace(/[?#].*$/, "");
  return (LEGAL_DOC_KEYS as readonly string[]).includes(key) ? (key as LegalDocKey) : undefined;
}

/** The plain text of a run of inline parts. */
export const legalPlainText = (parts: readonly LegalInline[]): string => parts.map((p) => p.text).join("");

/** A content-derived label for a block (the basis of its React key). */
export function legalBlockLabel(block: LegalBlock): string {
  if (block.kind === "h3") return `h3:${block.text}`;
  if (block.kind === "p") return `p:${legalPlainText(block.parts)}`;
  return `${block.kind}:${block.items.map(legalPlainText).join("|")}`;
}

/** Pairs each item with a stable key derived from its content (unique within the list). */
export function legalKeyed<T>(items: readonly T[], label: (item: T) => string): [string, T][] {
  const seen = new Map<string, number>();
  return items.map((item) => {
    const base = label(item);
    const n = seen.get(base) ?? 0;
    seen.set(base, n + 1);
    return [n === 0 ? base : `${base}#${n}`, item];
  });
}

export const LEGAL_DOCS: Readonly<Record<LegalDocKey, LegalDoc>> = {
  "privacy": {
    "key": "privacy",
    "title": "Privacy Notice",
    "kicker": "Privacy",
    "lede": "What we collect, why we need it, who else handles it, how long we keep it, and the rights you have over it.",
    "version": "2026-10-01",
    "effective": "2026-10-01",
    "effectiveLabel": "1 October 2026",
    "intro": [
      {
        "kind": "p",
        "parts": [
          {
            "text": "This notice covers the Oguaa website at oguaaman.com, the web app at citizen.oguaaman.com, the creator studio, the staff console and the Oguaa mobile app for iPhone and Android. It is written to meet Ghana's Data Protection Act, 2012 (Act 843) and the privacy rules of the Apple App Store and Google Play. The same text is published on the web and in the app."
          }
        ]
      }
    ],
    "sections": [
      {
        "heading": "Who we are and how to reach us",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Oguaa is an independent community platform for Cape Coast (Oguaa), in the Central Region of Ghana, and its people at home and abroad. It is operated by Dev Track, a business registered in Ghana (registration number BN843072020), whose address is Ghana Post GPS digital address GE-161-2814. Dev Track decides why and how your personal data is used on Oguaa, so it is the data controller for the processing described here. In this notice, \"Oguaa\", \"we\" and \"us\" mean Dev Track operating Oguaa."
              }
            ]
          },
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Data-rights requests:",
                  "bold": true
                },
                {
                  "text": " use the form at "
                },
                {
                  "text": "citizen.oguaaman.com/privacy/request",
                  "href": "/privacy/request"
                },
                {
                  "text": ". You don't need an account. You get a reference number, and we reply within 40 days (21 days for an objection)."
                }
              ],
              [
                {
                  "text": "Email:",
                  "bold": true
                },
                {
                  "text": " "
                },
                {
                  "text": "hello@oguaaman.com",
                  "href": "mailto:hello@oguaaman.com"
                },
                {
                  "text": ". Put \"Privacy\" in the subject line."
                }
              ],
              [
                {
                  "text": "Phone:",
                  "bold": true
                },
                {
                  "text": " +233 55 518 0048."
                }
              ],
              [
                {
                  "text": "Post:",
                  "bold": true
                },
                {
                  "text": " Dev Track, Ghana Post GPS digital address GE-161-2814."
                }
              ],
              [
                {
                  "text": "Deleting your account:",
                  "bold": true
                },
                {
                  "text": " see "
                },
                {
                  "text": "citizen.oguaaman.com/account/delete",
                  "href": "/account/delete"
                },
                {
                  "text": "."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "The short version",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "You must be 18 or older to have an account."
                }
              ],
              [
                {
                  "text": "Your email address and phone number are never shown on your public profile, and other members can't look them up."
                }
              ],
              [
                {
                  "text": "Your password is stored only as a one-way hash. We never see it."
                }
              ],
              [
                {
                  "text": "We don't sell your data, we don't show advertising, and we don't use advertising or analytics trackers."
                }
              ],
              [
                {
                  "text": "Some things you post are public by design: your profile, your listings, tributes, reviews and notices. Some safety notices are published straight away and checked afterwards."
                }
              ],
              [
                {
                  "text": "Payments are handled by payment providers. We never see or store your card number or Mobile Money PIN."
                }
              ],
              [
                {
                  "text": "You can download a copy of your data or delete your account at any time."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "What we collect and why",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "For each kind of data we say where it comes from, what we use it for, and the legal basis under Act 843: your "
              },
              {
                "text": "consent",
                "bold": true
              },
              {
                "text": ", a "
              },
              {
                "text": "contract",
                "bold": true
              },
              {
                "text": " with you (providing the service you asked for), a "
              },
              {
                "text": "legal obligation",
                "bold": true
              },
              {
                "text": ", or our "
              },
              {
                "text": "legitimate interest",
                "bold": true
              },
              {
                "text": " in running a safe community platform. Items marked \"required\" are needed for that feature to work. Without them you can't use it, but you can still use the rest of Oguaa."
              }
            ]
          },
          {
            "kind": "h3",
            "text": "Your account"
          },
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Email address or phone number",
                  "bold": true
                },
                {
                  "text": " (required to join). Used to sign you in, send sign-in, verification and password-reset codes, and send the account, safety and transaction messages you need. Basis: contract."
                }
              ],
              [
                {
                  "text": "Password",
                  "bold": true
                },
                {
                  "text": " (required). Stored only as a salted bcrypt hash, which cannot be turned back into your password. Basis: contract."
                }
              ],
              [
                {
                  "text": "Date of birth",
                  "bold": true
                },
                {
                  "text": " (required to join). Checked once when you sign up to confirm you are 18 or older. "
                },
                {
                  "text": "We do not store it.",
                  "bold": true
                },
                {
                  "text": " We keep only the date your age was confirmed. Basis: legal obligation and legitimate interest (keeping minors off the platform)."
                }
              ],
              [
                {
                  "text": "Your agreement to these terms:",
                  "bold": true
                },
                {
                  "text": " which versions of the Terms of Use and this notice you accepted, when, and on which app. Basis: legal obligation."
                }
              ],
              [
                {
                  "text": "Two-factor sign-in, if you turn it on:",
                  "bold": true
                },
                {
                  "text": " your authenticator secret, encrypted with AES-256-GCM, and your backup codes, stored as bcrypt hashes. Basis: contract."
                }
              ],
              [
                {
                  "text": "Security records:",
                  "bold": true
                },
                {
                  "text": " failed sign-in counts (used to lock an account under attack), when you last changed your password or two-factor settings, and your active sign-in sessions. Basis: legitimate interest (account security)."
                }
              ]
            ]
          },
          {
            "kind": "h3",
            "text": "Your profile"
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "Everything here is optional, and you choose what to add: display name (required to join), photo, bio, quarter or town, Asafo company, schools, web links, the city and country you live in if you live abroad, and a birthday as a month and day only (never a year). Your birthday is shown to others only if you switch on \"broadcast my birthday\". Your profile is shown publicly because that is the point of a community directory. Basis: contract and consent."
              }
            ]
          },
          {
            "kind": "h3",
            "text": "What you post"
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "Listings (businesses, events, places, projects, campaigns, properties, opportunities, memorials and more), photos, tributes, candles, reviews, news articles, safety incident reports and lost & found notices. These are public once published. Basis: contract."
              }
            ]
          },
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Photos",
                  "bold": true
                },
                {
                  "text": " you upload through our own server have their hidden location and camera details (EXIF metadata) removed before they are stored."
                }
              ],
              [
                {
                  "text": "Safety incident reports",
                  "bold": true
                },
                {
                  "text": " include the category, a description, where it happened and how to reach you. Your contact details are never shown publicly. Only you and the safety staff (curators, stewards and moderators) can see them."
                }
              ],
              [
                {
                  "text": "Lost & found notices",
                  "bold": true
                },
                {
                  "text": " include a description, the last-seen place, an optional photo and, for a missing person, the guardian details and police reference you give. People reply through Oguaa's message relay, so your contact details are never published."
                }
              ],
              [
                {
                  "text": "Crime and medical reports, notices about missing children, and any post our automated screen holds",
                  "bold": true
                },
                {
                  "text": " are checked by a curator before anyone else can see them. Other safety and lost & found notices are published straight away because they are time-critical, and staff review them afterwards."
                }
              ]
            ]
          },
          {
            "kind": "h3",
            "text": "Payments"
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "When you buy a ticket, make a pledge or donation, subscribe a business, promote a listing, place a shop order or fund an Oguaa Outside job, we keep: the amount, what it was for, the payment reference and status, the date, and the email address the receipt goes to. For a shop order we also keep the buyer's name, email, phone number, delivery address and note, because the seller needs them to fulfil the order. Basis: contract and legal obligation (tax and accounting records)."
              }
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "Card and Mobile Money details go straight to the payment provider (Paystack, Stripe or Apple). Oguaa never receives or stores your card number, security code or Mobile Money PIN."
              }
            ]
          },
          {
            "kind": "h3",
            "text": "Selling on Oguaa and business verification"
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "To take payments in a shop, a business owner gives us: the business's legal name, registration number and tax identification number (TIN), the owner's Ghana Card number, identity documents, a settlement bank or Mobile Money account, a GhanaPost GPS address and a business contact email or phone. Identity documents are stored encrypted with AES-256-GCM and can be opened only by you and our vetting staff, never through a public link. Buyers see the seller's legal name, location, business contact details, registration number and verification date on product pages, as consumer law requires. Basis: contract and legal obligation."
              }
            ]
          },
          {
            "kind": "h3",
            "text": "Oguaa Outside agents"
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "To be vetted as an agent you give us: an identity document (stored encrypted, as above), a guarantor's name and phone number, your payout Mobile Money or bank details, and the services and areas you cover. We keep your jobs, escrow payments, disputes and reviews. Tell your guarantor that you are sharing their details with us. Basis: contract and legitimate interest (protecting clients)."
              }
            ]
          },
          {
            "kind": "h3",
            "text": "Bookings, affiliates and institutions"
          },
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Artist booking requests:",
                  "bold": true
                },
                {
                  "text": " your name, contact details and event details are shared with the artist you ask to book."
                }
              ],
              [
                {
                  "text": "Affiliate programmes:",
                  "bold": true
                },
                {
                  "text": " your affiliate code, payout details and commission records."
                }
              ],
              [
                {
                  "text": "Institution roles:",
                  "bold": true
                },
                {
                  "text": " the schools, assemblies or organisations you manage or work for on Oguaa, and what you did in that role."
                }
              ]
            ]
          },
          {
            "kind": "h3",
            "text": "Messages and notifications"
          },
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "In-app notifications",
                  "bold": true
                },
                {
                  "text": ", and your choices about which kinds you receive."
                }
              ],
              [
                {
                  "text": "Push notifications:",
                  "bold": true
                },
                {
                  "text": " if you turn them on, a push token for your browser or device."
                }
              ],
              [
                {
                  "text": "Email and WhatsApp:",
                  "bold": true
                },
                {
                  "text": " we use your email address or phone number to deliver the messages you have chosen."
                }
              ]
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "Safety alerts, account messages and transaction messages are always sent, through the channels you have switched on. Community and remembrance notices are on until you switch them off. News about Oguaa itself (\"product\" messages) is off until you switch it on. You can change all of this in your notification settings. Every email also lets you unsubscribe: use your email app's unsubscribe button, or the link at the bottom of the email and then confirm. Basis: contract and consent."
              }
            ]
          },
          {
            "kind": "h3",
            "text": "The writing assistant"
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "The writing assistant is optional and works only after you agree to its terms. It sends the text you choose to Anthropic (Claude), a company in the United States, to write a suggestion. Before the text leaves Oguaa, email addresses, phone numbers and Ghana Card numbers are replaced with placeholders, so the provider doesn't see them. Don't include other private details. We keep a daily count of how often you used the assistant, but not the text itself. The assistant writes suggestions only and never makes decisions about you. You can withdraw your consent at any time. Basis: consent."
              }
            ]
          },
          {
            "kind": "h3",
            "text": "Reports, blocks and moderation"
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "When you report or block someone, we keep the report or block. When someone reports content, we keep a snapshot of it as evidence. We also keep the moderation decisions staff make and the results of our automated content screen, which can hold a post for a person to review. Basis: legitimate interest (a safe community) and legal obligation."
              }
            ]
          },
          {
            "kind": "h3",
            "text": "Technical data"
          },
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "IP address:",
                  "bold": true
                },
                {
                  "text": " used to limit repeated requests (for example, too many sign-in attempts), and recorded in security logs for sign-ins and staff actions."
                }
              ],
              [
                {
                  "text": "Listing views:",
                  "bold": true
                },
                {
                  "text": " to count unique views, we record your member ID (or, if you aren't signed in, your IP address) once per listing per day, and delete the record after 30 days."
                }
              ],
              [
                {
                  "text": "Location:",
                  "bold": true
                },
                {
                  "text": " only when you choose \"use my location\" on a map. On the explore map, your position goes from your device to the routing service to draw walking directions. On a listing form, the place you pick is saved with the listing."
                }
              ]
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "Basis: legitimate interest (security, preventing abuse, basic statistics) and, for location, your choice to share it."
              }
            ]
          },
          {
            "kind": "h3",
            "text": "Privacy requests"
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "When you make a data-rights request, we keep your name, contact details, the request and our handling of it. Basis: legal obligation."
              }
            ]
          }
        ]
      },
      {
        "heading": "Who can see your data",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Everyone:",
                  "bold": true
                },
                {
                  "text": " your public profile and everything published that you posted."
                }
              ],
              [
                {
                  "text": "Other members:",
                  "bold": true
                },
                {
                  "text": " the people you deal with see what the transaction needs. A seller sees a buyer's order details until 30 days after the order is fulfilled. An artist sees your booking request. The person who posted a lost & found notice receives your relayed message."
                }
              ],
              [
                {
                  "text": "Oguaa staff:",
                  "bold": true
                },
                {
                  "text": " curators, stewards, moderators, editors and vetting officers see what they need for their role. Staff accounts must use two-factor sign-in, and every staff look at an identity document is recorded."
                }
              ],
              [
                {
                  "text": "Service providers:",
                  "bold": true
                },
                {
                  "text": " the companies below process data for us."
                }
              ],
              [
                {
                  "text": "Authorities:",
                  "bold": true
                },
                {
                  "text": " a court, the police or a regulator when the law requires it, or when a child or someone else is at risk (see our "
                },
                {
                  "text": "Child Safety Standards",
                  "href": "/child-safety"
                },
                {
                  "text": ")."
                }
              ]
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "We never sell personal data and never share it for advertising."
              }
            ]
          }
        ]
      },
      {
        "heading": "Service providers and transfers abroad",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "These providers process personal data for us, only to deliver their service:"
              }
            ]
          },
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Paystack",
                  "bold": true
                },
                {
                  "text": " (card and Mobile Money payments): your receipt email, the amount and a reference. Only when you pay or are paid."
                }
              ],
              [
                {
                  "text": "Stripe",
                  "bold": true
                },
                {
                  "text": " (card payments in the mobile app): your card details and the amount. Only when you use it."
                }
              ],
              [
                {
                  "text": "Apple",
                  "bold": true
                },
                {
                  "text": " (in-app purchases on iPhone): the purchase record. Only when you use it."
                }
              ],
              [
                {
                  "text": "Anthropic",
                  "bold": true
                },
                {
                  "text": " (the writing assistant, United States): the redacted text you send. Only when you use it."
                }
              ],
              [
                {
                  "text": "Moonshot AI",
                  "bold": true
                },
                {
                  "text": " (Kimi, a backup writing assistant, China): would receive the same redacted text, but only if the main assistant fails and the backup is switched on. It is "
                },
                {
                  "text": "switched off",
                  "bold": true
                },
                {
                  "text": " on the live service. We will update this notice before switching it on."
                }
              ],
              [
                {
                  "text": "Resend",
                  "bold": true
                },
                {
                  "text": " (email delivery): your email address and the message."
                }
              ],
              [
                {
                  "text": "Meta",
                  "bold": true
                },
                {
                  "text": " (WhatsApp Business, message delivery): your phone number and the message. Only when you receive WhatsApp messages."
                }
              ],
              [
                {
                  "text": "Expo, Google, Apple and Mozilla push services",
                  "bold": true
                },
                {
                  "text": " (push notification delivery): a device or browser push token and the alert. Only when you turn on notifications."
                }
              ],
              [
                {
                  "text": "Cloudinary",
                  "bold": true
                },
                {
                  "text": " (image hosting): the images you upload, when image hosting is switched on."
                }
              ],
              [
                {
                  "text": "MongoDB Atlas",
                  "bold": true
                },
                {
                  "text": " (database hosting): all platform data."
                }
              ],
              [
                {
                  "text": "Render",
                  "bold": true
                },
                {
                  "text": " (API hosting, Frankfurt, Germany): all platform data in transit, plus server logs."
                }
              ],
              [
                {
                  "text": "Vercel",
                  "bold": true
                },
                {
                  "text": " (website hosting): your IP address and the pages you request."
                }
              ],
              [
                {
                  "text": "OpenStreetMap",
                  "bold": true
                },
                {
                  "text": " (map tiles and place search) "
                },
                {
                  "text": "and the OSRM routing service",
                  "bold": true
                },
                {
                  "text": " (walking directions): your IP address, the map area or place you search for and, for directions, your position. Your device sends these directly when you use a map."
                }
              ],
              [
                {
                  "text": "Google Fonts",
                  "bold": true
                },
                {
                  "text": " (web fonts on the websites) "
                },
                {
                  "text": "and unpkg",
                  "bold": true
                },
                {
                  "text": " (the map library in the mobile app): your IP address when the page loads."
                }
              ],
              [
                {
                  "text": "Google Maps:",
                  "bold": true
                },
                {
                  "text": " only if you tap \"Directions\" or \"Open in Google Maps\", which opens Google's own service."
                }
              ]
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "Our servers are in Germany, and several providers are in the United States or other countries. Your data therefore leaves Ghana. We send each provider only what it needs for its task. We use providers that publish data-protection and security commitments. Traffic to and from Oguaa is encrypted (HTTPS). If we add a provider or change what one receives, we update this notice first."
              }
            ]
          }
        ]
      },
      {
        "heading": "How long we keep it",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Account and profile:",
                  "bold": true
                },
                {
                  "text": " until you delete your account."
                }
              ],
              [
                {
                  "text": "Things you post:",
                  "bold": true
                },
                {
                  "text": " until you or staff remove them, or you delete your account (see below)."
                }
              ],
              [
                {
                  "text": "Sign-in, verification and password-reset codes:",
                  "bold": true
                },
                {
                  "text": " 10 minutes. Two-factor sign-in challenges: 5 minutes. Account-deletion codes: 15 minutes."
                }
              ],
              [
                {
                  "text": "Sign-in sessions:",
                  "bold": true
                },
                {
                  "text": " 30 days, or until you sign out on that device, change or reset your password, or turn two-factor sign-in on or off."
                }
              ],
              [
                {
                  "text": "In-app notifications:",
                  "bold": true
                },
                {
                  "text": " 12 months."
                }
              ],
              [
                {
                  "text": "Writing-assistant usage counts:",
                  "bold": true
                },
                {
                  "text": " 90 days."
                }
              ],
              [
                {
                  "text": "Listing-view records:",
                  "bold": true
                },
                {
                  "text": " 30 days."
                }
              ],
              [
                {
                  "text": "A buyer's contact details, as seen by the seller:",
                  "bold": true
                },
                {
                  "text": " until 30 days after the order is fulfilled. After that the seller sees only an initial."
                }
              ],
              [
                {
                  "text": "Identity and verification documents:",
                  "bold": true
                },
                {
                  "text": " until you delete your account, or earlier if you ask. We delete them when your account is deleted."
                }
              ],
              [
                {
                  "text": "Payment records",
                  "bold": true
                },
                {
                  "text": " (tickets, pledges, subscriptions, promotions, orders, escrow jobs): kept after you delete your account for tax, accounting and payment-dispute purposes, with your name, email, phone number and address removed. App Store purchase records are kept for 6 years, without your identity."
                }
              ],
              [
                {
                  "text": "Reports, moderation, audit and privacy-request records:",
                  "bold": true
                },
                {
                  "text": " kept without your name, so we can show how the platform was run and how your request was handled."
                }
              ],
              [
                {
                  "text": "Server logs:",
                  "bold": true
                },
                {
                  "text": " kept briefly by our hosting provider for security and fault-finding."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Deleting your account",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "You can delete your account from your account settings on the web or in the app. If you can't sign in, request deletion at "
              },
              {
                "text": "citizen.oguaaman.com/account/delete",
                "href": "/account/delete"
              },
              {
                "text": " and confirm with a code we send you."
              }
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "When you delete your account, we delete your profile, contact details, password, uploaded files, identity documents, blocks, follows, notifications, push registrations and usage counts. Photos and videos you uploaded that still appear on content that stays up (an institution's page, a published article or another member's page) stay with that content, no longer linked to you. Records we must keep are moved off your account id onto a new random one. Your listings are taken down and their contact details removed, except listings you posted for an institution, which stay with it. Reviews, tributes and news articles you wrote stay up under \"Former member\", with your name removed. The records listed under \"How long we keep it\" are kept without your identity. If you are a party to a funded escrow job or have unfulfilled paid orders, you need to settle those first."
              }
            ]
          }
        ]
      },
      {
        "heading": "Your rights",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Under Act 843 you have the right to:"
              }
            ]
          },
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Be informed:",
                  "bold": true
                },
                {
                  "text": " that is what this notice is for."
                }
              ],
              [
                {
                  "text": "Access your data:",
                  "bold": true
                },
                {
                  "text": " download a full copy, including this processing information, from your account settings, or ask through "
                },
                {
                  "text": "the request form",
                  "href": "/privacy/request"
                },
                {
                  "text": "."
                }
              ],
              [
                {
                  "text": "Correct your data:",
                  "bold": true
                },
                {
                  "text": " edit your profile at any time, or ask us to correct anything else."
                }
              ],
              [
                {
                  "text": "Delete your data:",
                  "bold": true
                },
                {
                  "text": " delete your account yourself, or ask us to delete specific data. The records we must keep are listed above."
                }
              ],
              [
                {
                  "text": "Object to processing:",
                  "bold": true
                },
                {
                  "text": " including to processing based on our legitimate interest. Objections are answered within 21 days."
                }
              ],
              [
                {
                  "text": "Withdraw your consent:",
                  "bold": true
                },
                {
                  "text": " at any time. Switch off the writing assistant, birthday broadcasts or notification categories in settings. Withdrawing consent doesn't affect anything done before."
                }
              ],
              [
                {
                  "text": "Stop marketing:",
                  "bold": true
                },
                {
                  "text": " we don't send marketing unless you switch on product news, and every email has an unsubscribe link."
                }
              ],
              [
                {
                  "text": "Not be subject to decisions made only by a computer:",
                  "bold": true
                },
                {
                  "text": " automated checks such as rate limits and our content screen can refuse a request or hold a post, but a person reviews anything held, and no decision with legal or similarly significant effects is made about you by automated means alone."
                }
              ],
              [
                {
                  "text": "Complain to the Data Protection Commission:",
                  "bold": true
                },
                {
                  "text": " if you are unhappy with how we handle your data, you can complain to Ghana's Data Protection Commission. We would welcome the chance to put things right first."
                }
              ]
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "People without an Oguaa account, for example someone named in a memorial or a news article, can use the same "
              },
              {
                "text": "request form",
                "href": "/privacy/request"
              },
              {
                "text": "."
              }
            ]
          }
        ]
      },
      {
        "heading": "How we protect your data",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "All traffic is encrypted (HTTPS), and the websites send strict security headers."
                }
              ],
              [
                {
                  "text": "Passwords and backup codes are stored as bcrypt hashes. Two-factor secrets and identity documents are encrypted with AES-256-GCM."
                }
              ],
              [
                {
                  "text": "Staff access depends on role, staff accounts must use two-factor sign-in, and staff access to sensitive records is logged."
                }
              ],
              [
                {
                  "text": "Sign-in attempts are rate-limited, and an account locks after repeated failures."
                }
              ],
              [
                {
                  "text": "Changing or resetting your password, or turning two-factor sign-in on or off, signs out every other session. Signing out ends the session on the device you sign out on."
                }
              ]
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "No system is perfectly secure. If a breach puts your data at risk, we will tell you and the Data Protection Commission as the law requires."
              }
            ]
          }
        ]
      },
      {
        "heading": "Children",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Oguaa is for adults aged 18 and over. We don't knowingly collect data from children, and we delete an account that belongs to a child as soon as we find out. Some notices are about children, for example a missing-child notice posted by a parent, guardian or relative, or by a teacher or official acting with the family's knowledge. These are checked by a curator before publication and taken down when the child is marked as found. See our "
              },
              {
                "text": "Child Safety Standards",
                "href": "/child-safety"
              },
              {
                "text": " and "
              },
              {
                "text": "Safeguarding Policy",
                "href": "/safeguarding"
              },
              {
                "text": "."
              }
            ]
          }
        ]
      },
      {
        "heading": "Changes to this notice",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "The version and effective date are shown at the bottom of this notice. If we make a significant change, we tell you in the app and ask you to review it before you continue."
              }
            ]
          }
        ]
      }
    ]
  },
  "terms": {
    "key": "terms",
    "title": "Terms of Use",
    "kicker": "Terms",
    "lede": "The agreement between you and Oguaa when you use the websites or the app.",
    "version": "2026-10-01",
    "effective": "2026-10-01",
    "effectiveLabel": "1 October 2026",
    "intro": [
      {
        "kind": "p",
        "parts": [
          {
            "text": "Oguaa is operated by Dev Track, a business registered in Ghana (registration number BN843072020), whose address is Ghana Post GPS digital address GE-161-2814. In these terms, \"Oguaa\", \"we\" and \"us\" mean Dev Track operating Oguaa."
          }
        ]
      },
      {
        "kind": "p",
        "parts": [
          {
            "text": "These terms apply to the Oguaa websites (oguaaman.com and citizen.oguaaman.com), the creator studio and the Oguaa mobile app. By creating an account or using Oguaa, you agree to them, to our "
          },
          {
            "text": "Acceptable Use Policy",
            "href": "/acceptable-use"
          },
          {
            "text": " and, when you buy or sell, to our "
          },
          {
            "text": "Terms of Sale",
            "href": "/terms-of-sale"
          },
          {
            "text": ". Our "
          },
          {
            "text": "Privacy Notice",
            "href": "/privacy"
          },
          {
            "text": " explains how we handle your personal data."
          }
        ]
      }
    ],
    "sections": [
      {
        "heading": "Who can join",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "You must be 18 or older. When you join, you confirm your age and agree to these terms. We remove accounts that belong to children."
                }
              ],
              [
                {
                  "text": "One person, one account. Use your real identity, and don't pretend to be someone else or an organisation you don't represent."
                }
              ],
              [
                {
                  "text": "Keep your password and any two-factor codes to yourself. You are responsible for what happens on your account. If you think someone else has used it, change your password and tell us."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Zero tolerance for objectionable content and abusive users",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Oguaa does not tolerate objectionable content or abusive behaviour. You must not post, upload or send anything that:"
              }
            ]
          },
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "sexually exploits or endangers children, in any form (see our "
                },
                {
                  "text": "Child Safety Standards",
                  "href": "/child-safety"
                },
                {
                  "text": ");"
                }
              ],
              [
                {
                  "text": "is sexually explicit, or shares intimate images of anyone without their consent;"
                }
              ],
              [
                {
                  "text": "harasses, bullies, threatens or intimidates anyone;"
                }
              ],
              [
                {
                  "text": "attacks people for their ethnicity, tribe, religion, gender, sexuality, disability or origin;"
                }
              ],
              [
                {
                  "text": "promotes violence, terrorism, self-harm or dangerous activities;"
                }
              ],
              [
                {
                  "text": "reveals someone's private information, such as their home address, phone number or ID numbers, without their permission;"
                }
              ],
              [
                {
                  "text": "is a scam, a fraud, spam, or impersonates a person, business or institution;"
                }
              ],
              [
                {
                  "text": "is false and harmful, or claims a death or a crime that didn't happen;"
                }
              ],
              [
                {
                  "text": "breaks the law or infringes someone else's rights."
                }
              ]
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "The full rules are in the "
              },
              {
                "text": "Acceptable Use Policy",
                "href": "/acceptable-use"
              },
              {
                "text": ". An automated screen checks posts for threats, slurs and explicit material. It can block a post or hold it for a person to review."
              }
            ]
          }
        ]
      },
      {
        "heading": "Reporting and blocking",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Report:",
                  "bold": true
                },
                {
                  "text": " every listing, profile, review, tribute, product, news article, agent and writing-assistant suggestion has a Report option. Choose the reason that fits. Child-safety and intimate-image reports hide the content straight away while we review it."
                }
              ],
              [
                {
                  "text": "Block:",
                  "bold": true
                },
                {
                  "text": " you can block any member from their profile. Once you block someone, neither of you sees the other's content or profile, and they can't follow you, contact you through Oguaa or review your business. You can unblock them at any time."
                }
              ],
              [
                {
                  "text": "Our response:",
                  "bold": true
                },
                {
                  "text": " our moderators review every report and act on it "
                },
                {
                  "text": "within 24 hours",
                  "bold": true
                },
                {
                  "text": ". We remove content that breaks these terms, and we suspend or permanently close the accounts of people who post it or who abuse others. We tell the person who reported what we decided."
                }
              ],
              [
                {
                  "text": "If someone is in immediate danger, call the police or emergency services first."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Removing content and closing accounts",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "We may refuse, hold, edit for clarity, unpublish or remove any content that breaks these terms or the Acceptable Use Policy, or that we must remove by law. We may suspend or permanently close an account for serious or repeated breaches, for abuse of other members or staff, for fraud, or when the law requires it. Suspending an account signs it out everywhere. We usually explain why we removed something or suspended an account. If you think we got it wrong, reply through the notice or use the "
              },
              {
                "text": "request form",
                "href": "/privacy/request"
              },
              {
                "text": ", and we will look at it again."
              }
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "You can close your account at any time from your account settings or at "
              },
              {
                "text": "citizen.oguaaman.com/account/delete",
                "href": "/account/delete"
              },
              {
                "text": "."
              }
            ]
          }
        ]
      },
      {
        "heading": "How content is reviewed",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Most contributions, including listings, memorials and projects, go to a curator and appear only once approved. Some things are published straight away, then reviewed: tributes, reviews, most safety incident reports and lost & found notices (because they are time-critical), campaigns from organisers we have already vetted, and news from verified authorities. Crime and medical incident reports, notices about missing children, and anything our automated screen holds always wait for a curator. Curators may decline a contribution, and when they do, they tell you why. You can fix it and resubmit."
              }
            ]
          }
        ]
      },
      {
        "heading": "Your content and the licence you give us",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "You keep ownership of what you post. By posting it, you give Oguaa a non-exclusive, royalty-free, worldwide licence to host, store, copy, resize, display and share it, only to run, show and promote Oguaa (for example, a preview when someone shares a link). The licence ends when you or we remove the content, except for copies we must keep under our "
              },
              {
                "text": "Privacy Notice",
                "href": "/privacy"
              },
              {
                "text": ", such as evidence for a report."
              }
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "Only post what is true and what you have the right to share. That includes photos you took, or photos you have permission to use. You are responsible for what you post."
              }
            ]
          }
        ]
      },
      {
        "heading": "Memorials and tributes",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Memorials honour real people who have died, and we handle them with extra care. A memorial's family can ask us to correct it or take it down at any time. Tributes must be respectful. The memorial's owner, its keeper and our staff can remove any tribute on it."
              }
            ]
          }
        ]
      },
      {
        "heading": "Oguaa's role in buying, selling and giving",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Oguaa is a platform. We are not the seller of goods and services listed by businesses, artists, event organisers, property owners or agents. They are responsible for what they sell, its description, its quality and delivery. The "
              },
              {
                "text": "Terms of Sale",
                "href": "/terms-of-sale"
              },
              {
                "text": " explain orders, refunds and disputes."
              }
            ]
          },
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Pledges and donations:",
                  "bold": true
                },
                {
                  "text": " Oguaa keeps a "
                },
                {
                  "text": "platform fee of 5%",
                  "bold": true
                },
                {
                  "text": " of each confirmed pledge. The rest goes to the project or campaign. The fee is shown before you pay. Pledges can't be refunded once confirmed, unless the campaign is cancelled or the payment was taken in error."
                }
              ],
              [
                {
                  "text": "Shop orders:",
                  "bold": true
                },
                {
                  "text": " Oguaa keeps a platform fee (currently 5%) from the seller's share. It doesn't increase the price you pay."
                }
              ],
              [
                {
                  "text": "Oguaa Outside:",
                  "bold": true
                },
                {
                  "text": " the client's payment is held in escrow until the job is done. If there is a dispute, a vetting officer decides whether the money is released to the agent or refunded to the client."
                }
              ],
              [
                {
                  "text": "Investment and opportunity notices",
                  "bold": true
                },
                {
                  "text": " are information from the people who post them. Oguaa is not a broker, lender, custodian or investment adviser. Do your own checks before committing money."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "The writing assistant",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "The writing assistant suggests wording. It can be wrong. Check what it writes before you post it, because you are responsible for anything you publish. It is available only after you agree to send your text to its provider, as explained in the "
              },
              {
                "text": "Privacy Notice",
                "href": "/privacy"
              },
              {
                "text": "."
              }
            ]
          }
        ]
      },
      {
        "heading": "Staff and institutions",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Curators, stewards, moderators, editors and vetting officers must use Oguaa's tools only for their role, keep what they see confidential, and use two-factor sign-in. Institution managers are responsible for what they publish for their institution."
              }
            ]
          }
        ]
      },
      {
        "heading": "Availability and liability",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "We work to keep Oguaa accurate and available, but it is provided \"as is\". Information posted by members, businesses and institutions is theirs, and we can't guarantee it. As far as the law allows, Oguaa is not liable for indirect losses, or for losses caused by other members, sellers or agents. Nothing in these terms limits rights you have under Ghanaian consumer law that cannot be excluded."
              }
            ]
          }
        ]
      },
      {
        "heading": "Changes to these terms",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "We may update these terms. The version and effective date are shown at the bottom. If a change is significant, we will tell you in the app and ask you to accept the new terms before you continue."
              }
            ]
          }
        ]
      },
      {
        "heading": "Governing law and contact",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "These terms are governed by the laws of the Republic of Ghana, and the courts of Ghana decide any dispute about them. Questions? Email "
              },
              {
                "text": "hello@oguaaman.com",
                "href": "mailto:hello@oguaaman.com"
              },
              {
                "text": " or call +233 55 518 0048."
              }
            ]
          }
        ]
      }
    ]
  },
  "acceptable-use": {
    "key": "acceptable-use",
    "title": "Acceptable Use Policy",
    "kicker": "Community standards",
    "lede": "How we keep Oguaa a place of pride, honesty and respect.",
    "version": "2026-10-01",
    "effective": "2026-10-01",
    "effectiveLabel": "1 October 2026",
    "intro": [
      {
        "kind": "p",
        "parts": [
          {
            "text": "This policy is part of our "
          },
          {
            "text": "Terms of Use",
            "href": "/terms"
          },
          {
            "text": ". It applies to everything you post, upload or send on Oguaa, including listings, photos, profiles, tributes, reviews, news, reports and messages sent through the relay. We have zero tolerance for content and behaviour that breaks it."
          }
        ]
      }
    ],
    "sections": [
      {
        "heading": "Be real and be local",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Post genuine people, places, businesses, events and stories. Don't invent businesses, projects or people."
                }
              ],
              [
                {
                  "text": "Don't pretend to be another person, a business, a traditional authority or a public institution."
                }
              ],
              [
                {
                  "text": "Don't post a death, crime or emergency that didn't happen, or a notice you know is false."
                }
              ],
              [
                {
                  "text": "Only claim a title or office that is really yours."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Be respectful",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "No harassment, bullying, threats or intimidation, whether against members, staff or anyone else."
                }
              ],
              [
                {
                  "text": "No hate: no attacks on people for their ethnicity, tribe, nationality, religion, gender, sexuality, disability or origin."
                }
              ],
              [
                {
                  "text": "Treat memorials and grieving families with care. No mocking the dead or their families."
                }
              ],
              [
                {
                  "text": "Don't encourage violence, self-harm or dangerous activities."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Keep people safe",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Anything that sexualises, exploits or endangers a child is never allowed. We remove it, close the account and report it to the authorities. See our "
                },
                {
                  "text": "Child Safety Standards",
                  "href": "/child-safety"
                },
                {
                  "text": "."
                }
              ],
              [
                {
                  "text": "No sexually explicit content, and never share intimate images of someone without their consent."
                }
              ],
              [
                {
                  "text": "Don't share other people's private information: home addresses, phone numbers, ID numbers, health details or photos of them in private settings."
                }
              ],
              [
                {
                  "text": "Only a parent, guardian or close relative, or a teacher or official acting with the family's knowledge, may post a notice about a missing child. Include the police reference where there is one."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Be honest in money matters",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "No scams, fake fundraising, pyramid schemes or misleading offers."
                }
              ],
              [
                {
                  "text": "Only sell physical goods and real-world services that you are allowed to sell. You can't sell digital downloads, weapons, drugs, counterfeit goods or anything illegal through Oguaa."
                }
              ],
              [
                {
                  "text": "Describe what you sell accurately, and honour the prices and terms you show."
                }
              ],
              [
                {
                  "text": "Don't ask people to pay outside Oguaa to avoid its protections, such as escrow for Oguaa Outside jobs."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Don't abuse the platform",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "No spam, repeated posts or automated scraping, and don't try to get around limits, blocks or suspensions."
                }
              ],
              [
                {
                  "text": "Don't try to reach accounts or data that aren't yours, or to disrupt the service."
                }
              ],
              [
                {
                  "text": "Don't upload malware, and don't use the writing assistant to produce content this policy forbids."
                }
              ],
              [
                {
                  "text": "Don't use Oguaa to settle contested chieftaincy, title or leadership disputes. We hold such claims and refer them to the recognised traditional and civic authorities."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Reporting and what happens next",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Use the Report option on any listing, profile, review, tribute, product, news article, agent or writing-assistant suggestion. Our moderators review every report within 24 hours. Child-safety and intimate-image reports hide the content immediately. You can also block any member from their profile."
              }
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "When content breaks this policy, we remove it. Depending on how serious it is, we also warn the person, suspend their account, or close it permanently. We report illegal content to the police or other authorities where the law requires, or where someone is at risk."
              }
            ]
          }
        ]
      }
    ]
  },
  "terms-of-sale": {
    "key": "terms-of-sale",
    "title": "Terms of Sale",
    "kicker": "Buying and selling",
    "lede": "What to expect when you pay for something on Oguaa, and what to do if it goes wrong.",
    "version": "2026-10-01",
    "effective": "2026-10-01",
    "effectiveLabel": "1 October 2026",
    "intro": [
      {
        "kind": "p",
        "parts": [
          {
            "text": "These terms apply when you buy from a shop, buy an event ticket, make a pledge or donation, book an artist or pay an Oguaa Outside agent through Oguaa. They add to our "
          },
          {
            "text": "Terms of Use",
            "href": "/terms"
          },
          {
            "text": ". They don't take away any rights you have under Ghanaian consumer protection law."
          }
        ]
      }
    ],
    "sections": [
      {
        "heading": "Who you are buying from",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Oguaa is the platform. The business, organiser, artist or agent is the seller and is responsible for what they sell. Before a shop can take payments, we verify its legal identity. Each product page shows the seller's legal name, location, business contact details and, where it has one, its registration number. Oguaa itself sells only its own services, such as business plans and listing promotions. For those, the supplier is Dev Track, the business that operates Oguaa: registration number BN843072020, Ghana Post GPS digital address GE-161-2814, phone +233 55 518 0048, email "
              },
              {
                "text": "hello@oguaaman.com",
                "href": "mailto:hello@oguaaman.com"
              },
              {
                "text": "."
              }
            ]
          }
        ]
      },
      {
        "heading": "Prices and payment",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Prices are shown in Ghana cedis (GH₵) and include everything you pay to the seller, apart from any delivery charge the seller shows you."
                }
              ],
              [
                {
                  "text": "You pay through Paystack (card or Mobile Money), or through Stripe (card, in the mobile app). Your card and Mobile Money details go directly to them. Oguaa never sees or stores them."
                }
              ],
              [
                {
                  "text": "Oguaa's platform fee (currently 5%) comes out of the seller's share. It doesn't increase the price you pay."
                }
              ],
              [
                {
                  "text": "A payment counts only when the payment provider confirms it. If a payment fails, no order, ticket or pledge is created."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Order confirmation and receipts",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "When your payment is confirmed, we show a confirmation with a reference number, and the payment provider emails a receipt to the address you gave. Keep the reference number: you'll need it if anything goes wrong. If you were signed in when you paid, your shop orders and tickets also appear in your account."
              }
            ]
          }
        ]
      },
      {
        "heading": "Shop orders",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Delivery or pickup:",
                  "bold": true
                },
                {
                  "text": " you choose at checkout. The seller prepares the order and tells you when it is ready or on its way."
                }
              ],
              [
                {
                  "text": "Cancelling:",
                  "bold": true
                },
                {
                  "text": " you can cancel an order before the seller dispatches it or marks it ready for pickup. Ask the seller, or contact us with your order reference. You get a full refund."
                }
              ],
              [
                {
                  "text": "Goods not delivered, or not as described:",
                  "bold": true
                },
                {
                  "text": " if your order doesn't arrive, or what arrives is faulty, damaged or clearly different from its description, contact the seller first. If the seller doesn't put it right, contact us within 14 days of the date the order should have arrived. You are entitled to a replacement, a repair or a full refund. If you return the goods, return them in the condition you received them."
                }
              ],
              [
                {
                  "text": "Change of mind:",
                  "bold": true
                },
                {
                  "text": " unless the seller's own policy says otherwise, you can't return goods just because you changed your mind. You can still cancel before dispatch."
                }
              ],
              [
                {
                  "text": "Services",
                  "bold": true
                },
                {
                  "text": " (for example a booked appointment): if the service isn't provided, or isn't provided as agreed, you are entitled to have it provided properly or to get your money back."
                }
              ],
              [
                {
                  "text": "Shops can't sell digital downloads or online content through Oguaa."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Event tickets",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Your ticket is issued when your payment is confirmed. Show its code at the door."
                }
              ],
              [
                {
                  "text": "If a ticket tier sells out while your payment is going through, no ticket is issued and your payment is refunded."
                }
              ],
              [
                {
                  "text": "If an event is cancelled,",
                  "bold": true
                },
                {
                  "text": " you get a full refund of the ticket price. If an event is moved to a new date, you can keep your ticket or ask for a refund before the new date."
                }
              ],
              [
                {
                  "text": "Otherwise, the organiser's own refund policy applies. It is shown on the event page before you buy."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Pledges and donations",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Oguaa keeps a platform fee of 5% of each confirmed pledge. The rest goes to the project or campaign. The fee and the amount the project receives are shown before you pay. Pledges and donations can't be refunded once confirmed, unless the campaign is cancelled or the payment was taken in error. A campaign stops taking pledges after its deadline."
              }
            ]
          }
        ]
      },
      {
        "heading": "Oguaa Outside jobs",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "The client agrees a quote with a vetted agent and pays it into escrow. The money is released to the agent when the client confirms the job is done. If there is a dispute, a vetting officer reviews both sides and decides whether to release the money to the agent or refund it to the client."
              }
            ]
          }
        ]
      },
      {
        "heading": "Business plans and promotions",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Business plans and listing promotions are Oguaa's own services. They aren't sold in the Oguaa mobile apps."
                }
              ],
              [
                {
                  "text": "A plan lasts for the period you pay for. It doesn't renew automatically: to keep it, pay again before it ends, and the new period is added on. To cancel, simply don't renew."
                }
              ],
              [
                {
                  "text": "A promotion runs for the number of days you buy."
                }
              ],
              [
                {
                  "text": "Because these services start straight away, they can't be refunded once they begin, unless they weren't delivered as described."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Disputes",
        "blocks": [
          {
            "kind": "ol",
            "items": [
              [
                {
                  "text": "Contact the seller, organiser or agent first. Most problems are solved this way."
                }
              ],
              [
                {
                  "text": "If that doesn't work, contact us at "
                },
                {
                  "text": "hello@oguaaman.com",
                  "href": "mailto:hello@oguaaman.com"
                },
                {
                  "text": " with your payment reference and what went wrong. We aim to reply within 14 days. Where the seller is at fault, we can require them to put it right, and we can arrange a refund through the payment provider."
                }
              ],
              [
                {
                  "text": "You can also use the dispute process of your card issuer or Mobile Money provider, or go to the consumer protection authorities or the courts of Ghana."
                }
              ]
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "These terms are governed by the laws of the Republic of Ghana."
              }
            ]
          }
        ]
      }
    ]
  },
  "child-safety": {
    "key": "child-safety",
    "title": "Child Safety Standards",
    "kicker": "Child safety",
    "lede": "Oguaa's standards against child sexual abuse and exploitation, and how to report a concern.",
    "version": "2026-10-01",
    "effective": "2026-10-01",
    "effectiveLabel": "1 October 2026",
    "intro": [
      {
        "kind": "p",
        "parts": [
          {
            "text": "These are the published child safety standards of Oguaa, the community platform for Cape Coast, for the Oguaa websites and the Oguaa mobile app on the App Store and Google Play."
          }
        ]
      }
    ],
    "sections": [
      {
        "heading": "Zero tolerance",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Oguaa has zero tolerance for child sexual abuse and exploitation (CSAE), including child sexual abuse material (CSAM). We never allow content, accounts or behaviour that sexualises, grooms, exploits, trafficks or endangers a child. This applies to images, video, text, links, profiles and messages sent through Oguaa, whether real or computer-generated."
              }
            ]
          }
        ]
      },
      {
        "heading": "Who can use Oguaa",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Oguaa accounts are for adults aged 18 and over. Everyone confirms their age when they join, and we remove accounts that belong to children. Oguaa has no private messaging or chat between members. The one exception is the lost & found relay: a signed-in member can send a single screened message to the person who posted a lost & found notice. Oguaa delivers it with the sender's name, there is no reply thread, and the poster's contact details are never shown. Youth and mentorship listings are public programme notices, and they must follow our "
              },
              {
                "text": "Safeguarding Policy",
                "href": "/safeguarding"
              },
              {
                "text": "."
              }
            ]
          }
        ]
      },
      {
        "heading": "How to report a concern",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "In the app or on the web:",
                  "bold": true
                },
                {
                  "text": " use Report on the listing, profile, tribute, review, news article or agent, and choose "
                },
                {
                  "text": "Child safety",
                  "bold": true
                },
                {
                  "text": ". You need to be signed in. Reported listings, tributes, reviews, news articles and agent profiles are hidden from public view immediately, and every child-safety report goes to the top of our moderators' queue."
                }
              ],
              [
                {
                  "text": "By email:",
                  "bold": true
                },
                {
                  "text": " write to "
                },
                {
                  "text": "hello@oguaaman.com",
                  "href": "mailto:hello@oguaaman.com"
                },
                {
                  "text": " with \"Child safety\" in the subject line and a link to what you saw. You don't need an account."
                }
              ],
              [
                {
                  "text": "Without an account:",
                  "bold": true
                },
                {
                  "text": " you can also use the "
                },
                {
                  "text": "request form",
                  "href": "/privacy/request"
                },
                {
                  "text": "."
                }
              ],
              [
                {
                  "text": "If a child is in immediate danger,",
                  "bold": true
                },
                {
                  "text": " contact the Ghana Police Service or emergency services first."
                }
              ]
            ]
          },
          {
            "kind": "p",
            "parts": [
              {
                "text": "Please don't copy, screenshot or forward abusive images of children, even to report them. Send us the link instead."
              }
            ]
          }
        ]
      },
      {
        "heading": "What we do",
        "blocks": [
          {
            "kind": "ol",
            "items": [
              [
                {
                  "text": "Remove:",
                  "bold": true
                },
                {
                  "text": " child-safety reports hide the content straight away wherever it can be hidden. When a moderator confirms abuse or exploitation, we remove it permanently. We act on every child-safety report within 24 hours."
                }
              ],
              [
                {
                  "text": "Preserve evidence:",
                  "bold": true
                },
                {
                  "text": " we keep a restricted copy of the reported content and the account details, so the authorities can investigate. Only authorised staff can access it."
                }
              ],
              [
                {
                  "text": "Close accounts:",
                  "bold": true
                },
                {
                  "text": " we suspend and permanently close accounts that post, share or seek such content."
                }
              ],
              [
                {
                  "text": "Report to the authorities:",
                  "bold": true
                },
                {
                  "text": " we report CSAM and child exploitation to the Ghana Police Service and the Cyber Security Authority under the Cybersecurity Act, 2020 (Act 1038), and to other national or international authorities where the law requires it or where it helps protect a child, such as the National Center for Missing & Exploited Children (NCMEC)."
                }
              ],
              [
                {
                  "text": "Co-operate:",
                  "bold": true
                },
                {
                  "text": " we respond to lawful requests from law enforcement investigating harm to children."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Missing and vulnerable children",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Only a parent, guardian or close relative, or a teacher or official acting with the family's knowledge, can post a notice about a missing child. They must confirm their relationship to the child, and a curator checks the notice before it is published. We take the notice down when the child is marked as found. We never show contact details on a public notice: replies go through Oguaa's relay."
              }
            ]
          }
        ]
      },
      {
        "heading": "Keeping these standards",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Our moderators treat child-safety reports as their top priority, and an automated screen holds posts that combine references to children with sexual language, so a person reviews them before anyone else sees them. We review these standards at least once a year and whenever the law or the app stores' requirements change."
              }
            ]
          }
        ]
      },
      {
        "heading": "Contact",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Oguaa's child safety point of contact is the Oguaa safety team at Dev Track, the business that operates Oguaa: "
              },
              {
                "text": "hello@oguaaman.com",
                "href": "mailto:hello@oguaaman.com"
              },
              {
                "text": ", subject line \"Child safety\", or +233 55 518 0048. The team can speak about our child safety practices and how we comply with the law."
              }
            ]
          }
        ]
      }
    ]
  },
  "safeguarding": {
    "key": "safeguarding",
    "title": "Youth & Guardian Consent Policy",
    "kicker": "Safeguarding",
    "lede": "How mentorship and youth-facing opportunities are kept safe.",
    "version": "2026-10-01",
    "effective": "2026-10-01",
    "effectiveLabel": "1 October 2026",
    "intro": [
      {
        "kind": "p",
        "parts": [
          {
            "text": "This policy works alongside our "
          },
          {
            "text": "Child Safety Standards",
            "href": "/child-safety"
          },
          {
            "text": ", which apply to everything on Oguaa."
          }
        ]
      }
    ],
    "sections": [
      {
        "heading": "Scope",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "This policy applies to mentorship, training and youth-facing opportunity listings on Oguaa. It covers those listings, how they are moderated, and the minimum information they must include before publication."
              }
            ]
          }
        ]
      },
      {
        "heading": "No direct matching chats on the platform",
        "blocks": [
          {
            "kind": "p",
            "parts": [
              {
                "text": "Oguaa does not offer private messaging between mentors and young people, anonymous messages, or one-click pairing. Listings are public programme notices that send people to the organiser's own official channel."
              }
            ]
          }
        ]
      },
      {
        "heading": "Safeguards for every programme",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Every mentorship listing must link to a publicly available safeguarding policy. We reject listings without one when they are submitted."
                }
              ],
              [
                {
                  "text": "A programme that involves anyone under 18 must require a parent or guardian's consent before they take part."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Guardian consent",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "If a mentorship programme includes children, the listing must say that guardian consent is required and explain clearly how the organiser collects it."
                }
              ],
              [
                {
                  "text": "The organiser collects and keeps the consent records. Oguaa does not store children's identity documents."
                }
              ]
            ]
          }
        ]
      },
      {
        "heading": "Moderation and enforcement",
        "blocks": [
          {
            "kind": "ul",
            "items": [
              [
                {
                  "text": "Curators may hold, reject or unpublish a mentorship listing that leaves out safeguarding controls, suggests unsafe ways of contacting young people, or appears to get around the guardian consent requirement."
                }
              ],
              [
                {
                  "text": "Repeated or high-risk breaches can lead to account suspension and, where required, a referral to the relevant authorities."
                }
              ],
              [
                {
                  "text": "To raise a concern about a youth programme, use Report on the listing and choose "
                },
                {
                  "text": "Child safety",
                  "bold": true
                },
                {
                  "text": ", or see how to reach us in the "
                },
                {
                  "text": "Child Safety Standards",
                  "href": "/child-safety"
                },
                {
                  "text": "."
                }
              ]
            ]
          }
        ]
      }
    ]
  }
};
