import { Link } from "react-router-dom";
import { Section } from "@/components/ui";
import { Reveal } from "@/components/motion";
import { PORTAL_URL } from "@/config";
import {
  LEGAL_DOCS,
  LEGAL_DOC_KEYS,
  legalBlockLabel,
  legalKeyed,
  legalPath,
  legalPlainText,
  type LegalBlock,
  type LegalDoc,
  type LegalDocKey,
  type LegalInline,
} from "@/content/legal.gen";

// Renders one of the canonical legal texts (docs/legal/*.md, generated by
// scripts/sync-legal.mjs) with the marketing site's look. The wording is
// identical to the portal and the mobile app.

/** Legal documents the marketing site serves itself; the rest live on the portal. */
const LOCAL_DOCS: ReadonlySet<string> = new Set<LegalDocKey>(["privacy", "terms"]);

const LINK_CLASS = "font-semibold text-green-text underline decoration-green/30 underline-offset-4 hover:decoration-green";

function DocLink({ href, children }: Readonly<{ href: string; children: string }>) {
  if (href.startsWith("/") && LOCAL_DOCS.has(href.slice(1))) {
    return <Link to={href} className={LINK_CLASS}>{children}</Link>;
  }
  const url = href.startsWith("/") ? `${PORTAL_URL}${href}` : href;
  return <a href={url} className={LINK_CLASS}>{children}</a>;
}

function Inline({ parts }: Readonly<{ parts: readonly LegalInline[] }>) {
  return (
    <>
      {legalKeyed(parts, (p) => `${p.href ?? ""}|${p.bold ? "b" : ""}|${p.text}`).map(([key, p]) => {
        if (p.href) return <DocLink key={key} href={p.href}>{p.text}</DocLink>;
        return p.bold ? <strong key={key} className="font-semibold text-ink">{p.text}</strong> : <span key={key}>{p.text}</span>;
      })}
    </>
  );
}

function Block({ block }: Readonly<{ block: LegalBlock }>) {
  if (block.kind === "h3") {
    return <h3 className="mt-6 text-xl font-semibold text-ink">{block.text}</h3>;
  }
  if (block.kind === "p") {
    return <p className="mt-4 leading-relaxed text-ink-muted"><Inline parts={block.parts} /></p>;
  }
  const items = legalKeyed(block.items, legalPlainText).map(([key, item]) => (
    <li key={key} className="pl-1 leading-relaxed"><Inline parts={item} /></li>
  ));
  return block.kind === "ol"
    ? <ol className="mt-4 list-decimal space-y-2 pl-6 text-ink-muted">{items}</ol>
    : <ul className="mt-4 list-disc space-y-2 pl-6 text-ink-muted">{items}</ul>;
}

function Blocks({ blocks }: Readonly<{ blocks: readonly LegalBlock[] }>) {
  return <>{legalKeyed(blocks, legalBlockLabel).map(([key, b]) => <Block key={key} block={b} />)}</>;
}

/** The body of a legal page: version line, text, and links to the other documents. */
export function LegalDocument({ doc }: Readonly<{ doc: LegalDoc }>) {
  return (
    <Section tone="paper" size="prose">
      <Reveal>
        <p className="text-sm text-ink-muted">Version {doc.version} · effective {doc.effectiveLabel}</p>
        <Blocks blocks={doc.intro} />
        {doc.sections.map((s) => (
          <section key={s.heading}>
            <h2 className="mt-10 text-2xl font-semibold text-ink sm:text-3xl">{s.heading}</h2>
            <Blocks blocks={s.blocks} />
          </section>
        ))}
        <nav aria-label="Legal documents" className="mt-12 flex flex-wrap gap-x-5 gap-y-2 border-t border-sand pt-6 text-sm">
          {LEGAL_DOC_KEYS.filter((k) => k !== doc.key).map((k) => (
            <DocLink key={k} href={legalPath(k)}>{LEGAL_DOCS[k].title}</DocLink>
          ))}
        </nav>
      </Reveal>
    </Section>
  );
}
