import { useState, type ReactNode } from "react";
import { Link, useLoaderData, type LoaderFunctionArgs } from "react-router-dom";
import { api } from "@/lib/api";
import type { Affiliate, AffiliateConversion, AffiliateProgramme, BusinessCoupon, BusinessVerification, CommerceOrder, Listing } from "@/lib/types";
import { Container } from "@/components/ui";
import { useAuth } from "@/lib/auth";
import { usePageTitle } from "@/lib/use-page-title";

export async function loader({ params }: LoaderFunctionArgs) {
  const business = await api.business(params.slug!);
  const [verification, orders, coupons, programmes, conversions] = await Promise.all([
    api.businessVerification(business.id).catch(() => null), api.businessOrders(business.id).catch(() => []), api.businessCoupons(business.id).catch(() => []), api.affiliateProgrammes(business.id).catch(() => []), api.affiliateConversions(business.id).catch(() => []),
  ]);
  const affiliates = (await Promise.all(programmes.map((programme) => api.affiliates(business.id, programme.id!).catch(() => [])))).flat();
  return { business, verification, orders, coupons, programmes, affiliates, conversions };
}
const field = "w-full rounded-lg border border-sand bg-paper px-3.5 py-2.5 text-sm text-ink";
export function Component() {
  const initial = useLoaderData() as { business: Listing; verification: BusinessVerification | null; orders: CommerceOrder[]; coupons: BusinessCoupon[]; programmes: AffiliateProgramme[]; affiliates: Affiliate[]; conversions: AffiliateConversion[] };
  const { member } = useAuth(); usePageTitle(`Commerce · ${initial.business.title}`);
  const [verification, setVerification] = useState(initial.verification); const [orders, setOrders] = useState(initial.orders); const [coupons, setCoupons] = useState(initial.coupons); const [message, setMessage] = useState("");
  const [kyc, setKyc] = useState({ legalName: verification?.legalName ?? "", registrationNumber: verification?.registrationNumber ?? "", taxIdentificationNo: verification?.taxIdentificationNo ?? "", ghanaCardNumber: verification?.ghanaCardNumber ?? "", businessPhone: verification?.businessPhone ?? "", ghanaPostGPS: verification?.ghanaPostGPS ?? "", documents: verification?.documents.join("\n") ?? "", settlementBankCode: verification?.settlementBankCode ?? "", settlementAccountNo: verification?.settlementAccountNo ?? "", settlementName: verification?.settlementName ?? "" });
  const [coupon, setCoupon] = useState<BusinessCoupon>({ code: "", discountType: "percent", discountValue: 10, active: true });
  const [programmes, setProgrammes] = useState(initial.programmes); const [conversions] = useState(initial.conversions);
  const [programme, setProgramme] = useState<AffiliateProgramme>({ name: "Store ambassadors", description: "Reward trusted partners for qualified product sales.", commissionBps: 1000, cookieWindowDays: 30, holdDays: 14, minimumPayoutPesewas: 5000, payoutMode: "mobile_money", active: true });
  const [affiliates, setAffiliates] = useState(initial.affiliates);
  const [affiliateStep, setAffiliateStep] = useState<"programme"|"partners"|"links"|"earnings">("programme");
  const [affiliate, setAffiliate] = useState<Affiliate>({ programmeId: initial.programmes[0]?.id ?? "", code: "", name: "", email: "", payoutPhone: "", promotionChannels: [], audienceSummary: "", status: "approved", active: true });
  if (!member || member.id !== initial.business.ownerId) return <Container className="py-20"><h1 className="text-4xl">Owner access required</h1></Container>;
  async function submitKyc() { try { setVerification(await api.submitBusinessVerification(initial.business.id, { ...kyc, documents: kyc.documents.split("\n").map((x) => x.trim()).filter(Boolean) })); setMessage("Verification submitted for review."); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not submit verification."); } }
  async function saveCoupon() { try { const saved = await api.saveBusinessCoupon(initial.business.id, coupon); setCoupons((rows) => [saved, ...rows.filter((x) => x.id !== saved.id)]); setCoupon({ code: "", discountType: "percent", discountValue: 10, active: true }); setMessage("Coupon saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not save coupon."); } }
  async function saveProgramme() { try { const saved=await api.saveAffiliateProgramme(initial.business.id,programme);setProgrammes((rows)=>[saved,...rows.filter((x)=>x.id!==saved.id)]);setAffiliate((x)=>({...x,programmeId:saved.id!}));setMessage("Affiliate programme saved."); } catch(e){setMessage(e instanceof Error?e.message:"Could not save programme.")} }
  async function saveAffiliate(){try{const saved=await api.saveAffiliate(initial.business.id,affiliate);setAffiliates((rows)=>[saved,...rows.filter((row)=>row.id!==saved.id)]);setAffiliate({...affiliate,code:"",name:"",email:"",payoutPhone:"",audienceSummary:""});setMessage("Affiliate approved. Their tracked campaign link is ready.")}catch(e){setMessage(e instanceof Error?e.message:"Could not add affiliate.")}}
  async function advance(order: CommerceOrder, status: CommerceOrder["status"]) { await api.setBusinessOrderStatus(initial.business.id, order.id, status); setOrders((rows) => rows.map((x) => x.id === order.id ? { ...x, status } : x)); }
  return <Container className="py-10"><Link to={`/business/${initial.business.slug}/manage`} className="text-sm font-semibold text-green-text">← Storefront editor</Link><h1 className="mt-4 text-4xl font-semibold">Commerce controls</h1><p className="mt-2 text-ink-muted">Private verification, Paystack settlement, orders and customer coupons for {initial.business.title}.</p>{message && <p role="status" className="mt-4 rounded-lg bg-gold/[0.1] p-3 text-sm text-gold-text">{message}</p>}
    <section className="mt-8 rounded-[var(--radius-card)] border border-sand bg-cream p-6"><div className="flex items-center justify-between gap-4"><div><p className="eyebrow">Trust &amp; settlement</p><h2 className="mt-1 text-2xl font-semibold">Business verification</h2></div><span className="rounded-full bg-paper px-3 py-1 text-xs font-semibold uppercase">{verification?.status ?? "not submitted"}</span></div>{verification?.reviewNote && <p className="mt-3 text-sm text-clay-text">Reviewer note: {verification.reviewNote}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(kyc).filter(([key]) => key !== "documents").map(([key, value]) => <input key={key} aria-label={key} placeholder={key.replace(/([A-Z])/g, " $1")} value={value} onChange={(e) => setKyc({ ...kyc, [key]: e.target.value })} className={field} />)}<textarea aria-label="Verification document URLs" placeholder="Three secure document URLs, one per line: registration certificate, Ghana Card front, Ghana Card back" value={kyc.documents} onChange={(e) => setKyc({ ...kyc, documents: e.target.value })} className={`${field} min-h-28 sm:col-span-2`} /></div><button type="button" onClick={submitKyc} className="mt-4 rounded-full bg-green px-5 py-2.5 font-semibold text-on-green">Submit for verification</button></section>
    <section className="mt-8 rounded-[var(--radius-card)] border border-sand bg-cream p-6"><p className="eyebrow">Sales growth</p><h2 className="mt-1 text-2xl font-semibold">Coupons</h2><div className="mt-4 grid gap-3 sm:grid-cols-4"><input aria-label="Coupon code" placeholder="OGUAA10" value={coupon.code} onChange={(e) => setCoupon({ ...coupon, code: e.target.value.toUpperCase() })} className={field}/><select aria-label="Discount type" value={coupon.discountType} onChange={(e) => setCoupon({ ...coupon, discountType: e.target.value as "percent" | "fixed" })} className={field}><option value="percent">Percentage</option><option value="fixed">Fixed pesewas</option></select><input aria-label="Discount value" type="number" value={coupon.discountValue} onChange={(e) => setCoupon({ ...coupon, discountValue: Number(e.target.value) })} className={field}/><input aria-label="Redemption limit" type="number" placeholder="Limit (0 unlimited)" onChange={(e) => setCoupon({ ...coupon, redemptionLimit: Number(e.target.value) })} className={field}/></div><button type="button" onClick={saveCoupon} className="mt-4 rounded-full bg-gold px-5 py-2.5 font-semibold text-green-900">Create coupon</button><div className="mt-5 grid gap-2">{coupons.map((c) => <div key={c.id} className="flex items-center justify-between rounded-lg border border-sand bg-paper p-3"><div><strong>{c.code}</strong><span className="ml-2 text-sm text-ink-muted">{c.discountType === "percent" ? `${c.discountValue}%` : `GH₵ ${(c.discountValue / 100).toFixed(2)}`} · {c.redemptions ?? 0} used</span></div><button type="button" onClick={async () => { await api.deleteBusinessCoupon(initial.business.id, c.id!); setCoupons((rows) => rows.filter((x) => x.id !== c.id)); }} className="text-sm font-semibold text-clay-text">Archive</button></div>)}</div></section>
    <section className="relative mt-8 overflow-hidden rounded-[var(--radius-card)] border border-sand bg-cream p-6"><Users aria-hidden className="pointer-events-none absolute -right-10 -top-8 h-48 w-48 text-teal opacity-[0.06]"/><div className="relative"><p className="eyebrow">Partner growth</p><h2 className="mt-1 text-3xl font-semibold">Affiliate marketing</h2><p className="mt-2 max-w-2xl text-sm text-ink-muted">Recruit trusted partners, issue persistent tracked links, review qualified sales and release commission after the return window.</p><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{([['programme','1. Rules'],['partners','2. Partners'],['links','3. Links'],['earnings','4. Earnings']] as const).map(([id,label])=><button type="button" key={id} onClick={()=>setAffiliateStep(id)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold ${affiliateStep===id?'bg-green text-on-green':'border border-sand bg-paper text-ink-muted'}`}>{label}</button>)}</div>
    {affiliateStep==='programme'&&<div className="mt-6"><div className="grid gap-3 sm:grid-cols-2"><input aria-label="Programme name" placeholder="Programme name" value={programme.name} onChange={(e)=>setProgramme({...programme,name:e.target.value})} className={field}/><input aria-label="Programme description" placeholder="What partners should promote" value={programme.description??''} onChange={(e)=>setProgramme({...programme,description:e.target.value})} className={field}/><input aria-label="Commission percent" type="number" min="0.01" max="50" value={programme.commissionBps/100} onChange={(e)=>setProgramme({...programme,commissionBps:Number(e.target.value)*100})} className={field}/><input aria-label="Cookie window days" type="number" min="1" max="365" value={programme.cookieWindowDays??30} onChange={(e)=>setProgramme({...programme,cookieWindowDays:Number(e.target.value)})} className={field}/><input aria-label="Hold days" type="number" min="0" max="180" value={programme.holdDays} onChange={(e)=>setProgramme({...programme,holdDays:Number(e.target.value)})} className={field}/><input aria-label="Minimum payout cedis" type="number" min="0" value={(programme.minimumPayoutPesewas??0)/100} onChange={(e)=>setProgramme({...programme,minimumPayoutPesewas:Number(e.target.value)*100})} className={field}/></div><button type="button" onClick={saveProgramme} className="mt-4 rounded-full bg-teal px-5 py-2.5 font-semibold text-white">Save programme rules</button></div>}
    {affiliateStep==='partners'&&<div className="mt-6"><div className="grid gap-3 sm:grid-cols-2"><select aria-label="Affiliate programme" value={affiliate.programmeId} onChange={(e)=>setAffiliate({...affiliate,programmeId:e.target.value})} className={field}><option value="">Choose programme</option>{programmes.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input aria-label="Affiliate code" placeholder="AMA10" value={affiliate.code} onChange={(e)=>setAffiliate({...affiliate,code:e.target.value.toUpperCase()})} className={field}/><input aria-label="Affiliate name" placeholder="Partner name" value={affiliate.name} onChange={(e)=>setAffiliate({...affiliate,name:e.target.value})} className={field}/><input aria-label="Affiliate email" type="email" placeholder="partner@example.com" value={affiliate.email} onChange={(e)=>setAffiliate({...affiliate,email:e.target.value})} className={field}/><input aria-label="Payout phone" placeholder="Mobile money number" value={affiliate.payoutPhone??''} onChange={(e)=>setAffiliate({...affiliate,payoutPhone:e.target.value})} className={field}/><input aria-label="Audience summary" placeholder="Audience and promotion approach" value={affiliate.audienceSummary??''} onChange={(e)=>setAffiliate({...affiliate,audienceSummary:e.target.value})} className={field}/></div><button type="button" disabled={!affiliate.programmeId||!affiliate.code||!affiliate.name||!affiliate.email} onClick={saveAffiliate} className="mt-4 rounded-full bg-green px-5 py-2.5 font-semibold text-on-green disabled:opacity-40">Approve affiliate</button><div className="mt-6 grid gap-3 sm:grid-cols-2">{affiliates.length===0?<p className="rounded-xl border border-dashed border-sand p-6 text-sm text-ink-muted">No affiliates yet. Add the first trusted partner above.</p>:affiliates.map((row)=><article key={row.id} className="rounded-xl border border-sand bg-paper p-4"><div className="flex justify-between gap-3"><div><strong>{row.name}</strong><p className="text-sm text-ink-muted">{row.email}</p></div><span className="h-fit rounded-full bg-teal/10 px-2.5 py-1 text-xs font-semibold text-teal-text">{row.code}</span></div><p className="mt-3 text-xs text-ink-faint">{row.status??(row.active?'approved':'paused')} · {row.payoutPhone||'Payout details pending'}</p></article>)}</div></div>}
    {affiliateStep==='links'&&<div className="mt-6 grid gap-3 sm:grid-cols-2">{affiliates.length===0?<p className="rounded-xl border border-dashed border-sand p-6 text-sm text-ink-muted">Approve a partner before creating tracked links.</p>:affiliates.map((row)=>{const url=`${window.location.origin}/business/${initial.business.slug}?aff=${row.code}`;return <article key={row.id} className="rounded-xl border border-sand bg-paper p-4"><Link2 className="mb-3 text-teal" size={20}/><strong>{row.name}'s main link</strong><p className="mt-2 break-all text-xs text-ink-muted">{url}</p><button type="button" onClick={()=>navigator.clipboard.writeText(url)} className="mt-3 inline-flex items-center gap-2 rounded-full border border-teal/30 px-3 py-1.5 text-xs font-semibold text-teal-text"><Copy size={13}/> Copy link</button></article>})}</div>}
    {affiliateStep==='earnings'&&<div className="mt-6"><div className="grid gap-3 sm:grid-cols-3"><AffiliateStat icon={<BarChart3 size={18}/>} label="Qualified sales" value={String(conversions.filter(c=>c.status!=='void').length)}/><AffiliateStat icon={<WalletCards size={18}/>} label="Pending commission" value={`GH₵ ${(conversions.filter(c=>c.status==='reserved'||c.status==='converted').reduce((n,c)=>n+c.commissionPesewas,0)/100).toFixed(2)}`}/><AffiliateStat icon={<WalletCards size={18}/>} label="Paid commission" value={`GH₵ ${(conversions.filter(c=>c.status==='paid').reduce((n,c)=>n+c.commissionPesewas,0)/100).toFixed(2)}`}/></div><div className="mt-4 space-y-2">{conversions.length===0?<p className="rounded-xl border border-dashed border-sand p-6 text-sm text-ink-muted">No attributed sales yet. Completed checkouts appear here automatically.</p>:conversions.map((c)=><p key={c.id} className="rounded-lg bg-paper p-3 text-sm"><strong>{c.affiliateCode}</strong> · {c.status} · GH₵ {(c.commissionPesewas/100).toFixed(2)} commission · {c.orderReference}</p>)}</div></div>}</div></section>
    <section className="mt-8 rounded-[var(--radius-card)] border border-sand bg-cream p-6"><p className="eyebrow">Fulfilment</p><h2 className="mt-1 text-2xl font-semibold">Orders</h2><div className="mt-5 space-y-3">{orders.length === 0 && <p className="text-ink-muted">Paid customer orders will appear here.</p>}{orders.map((o) => <article key={o.id} className="rounded-lg border border-sand bg-paper p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{o.reference}</strong><p className="text-sm text-ink-muted">{o.buyerName} · {o.buyerPhone} · {o.fulfilment}</p></div><div className="text-right"><strong>GH₵ {(o.amountPesewas / 100).toFixed(2)}</strong><p className="text-xs text-ink-faint">You receive GH₵ {(o.businessNetPesewas / 100).toFixed(2)}</p></div></div><p className="mt-2 text-sm">{o.lines.map((l) => `${l.quantity}× ${l.name}`).join(", ")}</p><div className="mt-3 flex flex-wrap gap-2">{(["processing", "ready", "fulfilled"] as const).map((status) => <button key={status} type="button" onClick={() => advance(o, status)} className={`rounded-full border px-3 py-1 text-xs font-semibold ${o.status === status ? "border-green bg-green text-on-green" : "border-sand"}`}>{status}</button>)}</div></article>)}</div></section>
  </Container>;
}

function AffiliateStat({icon,label,value}:Readonly<{icon:ReactNode;label:string;value:string}>){return <div className="rounded-xl border border-sand bg-paper p-4"><span className="text-teal">{icon}</span><p className="mt-3 text-xs font-semibold uppercase tracking-wider text-ink-faint">{label}</p><p className="mt-1 text-xl font-semibold text-ink">{value}</p></div>}

type GlyphProps = Readonly<{ className?: string; size?: number; "aria-hidden"?: boolean }>;
function Glyph({ className = "", size = 18, children }: GlyphProps & { children: ReactNode }) { return <span aria-hidden className={`inline-grid place-items-center ${className}`} style={{ width: size, height: size }}>{children}</span>; }
function Users(props: GlyphProps) { return <Glyph {...props}>◎</Glyph>; }
function Link2(props: GlyphProps) { return <Glyph {...props}>↗</Glyph>; }
function Copy(props: GlyphProps) { return <Glyph {...props}>▣</Glyph>; }
function BarChart3(props: GlyphProps) { return <Glyph {...props}>▥</Glyph>; }
function WalletCards(props: GlyphProps) { return <Glyph {...props}>₵</Glyph>; }
