import { useState } from "react";
import { Link, useLoaderData, type LoaderFunctionArgs } from "react-router-dom";
import { api } from "@/lib/api";
import type { Affiliate, AffiliateConversion, AffiliateProgramme, BusinessCoupon, BusinessVerification, CommerceOrder, Listing } from "@/lib/types";
import { Container } from "@/components/ui";
import { useAuth } from "@/lib/auth";
import { usePageTitle } from "@/lib/use-page-title";

export async function loader({ params }: LoaderFunctionArgs) {
  const business = await api.business(params.slug!);
  const [verification, orders, coupons, programmes, conversions] = await Promise.all([
    api.businessVerification(business.id).catch(() => null), api.businessOrders(business.id).catch(() => []), api.businessCoupons(business.id).catch(() => []), api.affiliateProgrammes(business.id).catch(() => []), api.affiliateConversions(business.id).catch(() => []),
  ]);
  return { business, verification, orders, coupons, programmes, conversions };
}
const field = "w-full rounded-lg border border-sand bg-paper px-3.5 py-2.5 text-sm text-ink";
export function Component() {
  const initial = useLoaderData() as { business: Listing; verification: BusinessVerification | null; orders: CommerceOrder[]; coupons: BusinessCoupon[]; programmes: AffiliateProgramme[]; conversions: AffiliateConversion[] };
  const { member } = useAuth(); usePageTitle(`Commerce · ${initial.business.title}`);
  const [verification, setVerification] = useState(initial.verification); const [orders, setOrders] = useState(initial.orders); const [coupons, setCoupons] = useState(initial.coupons); const [message, setMessage] = useState("");
  const [kyc, setKyc] = useState({ legalName: verification?.legalName ?? "", registrationNumber: verification?.registrationNumber ?? "", taxIdentificationNo: verification?.taxIdentificationNo ?? "", ghanaCardNumber: verification?.ghanaCardNumber ?? "", businessPhone: verification?.businessPhone ?? "", ghanaPostGPS: verification?.ghanaPostGPS ?? "", documents: verification?.documents.join("\n") ?? "", settlementBankCode: verification?.settlementBankCode ?? "", settlementAccountNo: verification?.settlementAccountNo ?? "", settlementName: verification?.settlementName ?? "" });
  const [coupon, setCoupon] = useState<BusinessCoupon>({ code: "", discountType: "percent", discountValue: 10, active: true });
  const [programmes, setProgrammes] = useState(initial.programmes); const [conversions] = useState(initial.conversions);
  const [programme, setProgramme] = useState<AffiliateProgramme>({ name: "Store ambassadors", commissionBps: 1000, holdDays: 14, active: true });
  const [affiliate, setAffiliate] = useState<Affiliate>({ programmeId: initial.programmes[0]?.id ?? "", code: "", name: "", email: "", active: true });
  if (!member || member.id !== initial.business.ownerId) return <Container className="py-20"><h1 className="text-4xl">Owner access required</h1></Container>;
  async function submitKyc() { try { setVerification(await api.submitBusinessVerification(initial.business.id, { ...kyc, documents: kyc.documents.split("\n").map((x) => x.trim()).filter(Boolean) })); setMessage("Verification submitted for review."); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not submit verification."); } }
  async function saveCoupon() { try { const saved = await api.saveBusinessCoupon(initial.business.id, coupon); setCoupons((rows) => [saved, ...rows.filter((x) => x.id !== saved.id)]); setCoupon({ code: "", discountType: "percent", discountValue: 10, active: true }); setMessage("Coupon saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not save coupon."); } }
  async function saveProgramme() { try { const saved=await api.saveAffiliateProgramme(initial.business.id,programme);setProgrammes((rows)=>[saved,...rows.filter((x)=>x.id!==saved.id)]);setAffiliate((x)=>({...x,programmeId:saved.id!}));setMessage("Affiliate programme saved."); } catch(e){setMessage(e instanceof Error?e.message:"Could not save programme.")} }
  async function saveAffiliate(){try{await api.saveAffiliate(initial.business.id,affiliate);setAffiliate({...affiliate,code:"",name:"",email:""});setMessage("Affiliate added. Share product links with ?aff=CODE.")}catch(e){setMessage(e instanceof Error?e.message:"Could not add affiliate.")}}
  async function advance(order: CommerceOrder, status: CommerceOrder["status"]) { await api.setBusinessOrderStatus(initial.business.id, order.id, status); setOrders((rows) => rows.map((x) => x.id === order.id ? { ...x, status } : x)); }
  return <Container className="py-10"><Link to={`/business/${initial.business.slug}/manage`} className="text-sm font-semibold text-green-text">← Storefront editor</Link><h1 className="mt-4 text-4xl font-semibold">Commerce controls</h1><p className="mt-2 text-ink-muted">Private verification, Paystack settlement, orders and customer coupons for {initial.business.title}.</p>{message && <p role="status" className="mt-4 rounded-lg bg-gold/[0.1] p-3 text-sm text-gold-text">{message}</p>}
    <section className="mt-8 rounded-[var(--radius-card)] border border-sand bg-cream p-6"><div className="flex items-center justify-between gap-4"><div><p className="eyebrow">Trust &amp; settlement</p><h2 className="mt-1 text-2xl font-semibold">Business verification</h2></div><span className="rounded-full bg-paper px-3 py-1 text-xs font-semibold uppercase">{verification?.status ?? "not submitted"}</span></div>{verification?.reviewNote && <p className="mt-3 text-sm text-clay-text">Reviewer note: {verification.reviewNote}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(kyc).filter(([key]) => key !== "documents").map(([key, value]) => <input key={key} aria-label={key} placeholder={key.replace(/([A-Z])/g, " $1")} value={value} onChange={(e) => setKyc({ ...kyc, [key]: e.target.value })} className={field} />)}<textarea aria-label="Verification document URLs" placeholder="Three secure document URLs, one per line: registration certificate, Ghana Card front, Ghana Card back" value={kyc.documents} onChange={(e) => setKyc({ ...kyc, documents: e.target.value })} className={`${field} min-h-28 sm:col-span-2`} /></div><button type="button" onClick={submitKyc} className="mt-4 rounded-full bg-green px-5 py-2.5 font-semibold text-on-green">Submit for verification</button></section>
    <section className="mt-8 rounded-[var(--radius-card)] border border-sand bg-cream p-6"><p className="eyebrow">Sales growth</p><h2 className="mt-1 text-2xl font-semibold">Coupons</h2><div className="mt-4 grid gap-3 sm:grid-cols-4"><input aria-label="Coupon code" placeholder="OGUAA10" value={coupon.code} onChange={(e) => setCoupon({ ...coupon, code: e.target.value.toUpperCase() })} className={field}/><select aria-label="Discount type" value={coupon.discountType} onChange={(e) => setCoupon({ ...coupon, discountType: e.target.value as "percent" | "fixed" })} className={field}><option value="percent">Percentage</option><option value="fixed">Fixed pesewas</option></select><input aria-label="Discount value" type="number" value={coupon.discountValue} onChange={(e) => setCoupon({ ...coupon, discountValue: Number(e.target.value) })} className={field}/><input aria-label="Redemption limit" type="number" placeholder="Limit (0 unlimited)" onChange={(e) => setCoupon({ ...coupon, redemptionLimit: Number(e.target.value) })} className={field}/></div><button type="button" onClick={saveCoupon} className="mt-4 rounded-full bg-gold px-5 py-2.5 font-semibold text-green-900">Create coupon</button><div className="mt-5 grid gap-2">{coupons.map((c) => <div key={c.id} className="flex items-center justify-between rounded-lg border border-sand bg-paper p-3"><div><strong>{c.code}</strong><span className="ml-2 text-sm text-ink-muted">{c.discountType === "percent" ? `${c.discountValue}%` : `GH₵ ${(c.discountValue / 100).toFixed(2)}`} · {c.redemptions ?? 0} used</span></div><button type="button" onClick={async () => { await api.deleteBusinessCoupon(initial.business.id, c.id!); setCoupons((rows) => rows.filter((x) => x.id !== c.id)); }} className="text-sm font-semibold text-clay-text">Archive</button></div>)}</div></section>
    <section className="mt-8 rounded-[var(--radius-card)] border border-sand bg-cream p-6"><p className="eyebrow">Partner sales</p><h2 className="mt-1 text-2xl font-semibold">Affiliate programme</h2><p className="mt-2 text-sm text-ink-muted">Business-funded commission is withheld in Paystack's split, held by Oguaa, and released after your return window.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><input aria-label="Programme name" value={programme.name} onChange={(e)=>setProgramme({...programme,name:e.target.value})} className={field}/><input aria-label="Commission percent" type="number" value={programme.commissionBps/100} onChange={(e)=>setProgramme({...programme,commissionBps:Number(e.target.value)*100})} className={field}/><input aria-label="Hold days" type="number" value={programme.holdDays} onChange={(e)=>setProgramme({...programme,holdDays:Number(e.target.value)})} className={field}/></div><button type="button" onClick={saveProgramme} className="mt-4 rounded-full bg-teal px-5 py-2.5 font-semibold text-white">Save programme</button>{programmes.length>0&&<div className="mt-6 grid gap-3 sm:grid-cols-4"><select aria-label="Affiliate programme" value={affiliate.programmeId} onChange={(e)=>setAffiliate({...affiliate,programmeId:e.target.value})} className={field}>{programmes.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input aria-label="Affiliate code" placeholder="AMA10" value={affiliate.code} onChange={(e)=>setAffiliate({...affiliate,code:e.target.value.toUpperCase()})} className={field}/><input aria-label="Affiliate name" placeholder="Affiliate name" value={affiliate.name} onChange={(e)=>setAffiliate({...affiliate,name:e.target.value})} className={field}/><input aria-label="Affiliate email" type="email" placeholder="Payout email" value={affiliate.email} onChange={(e)=>setAffiliate({...affiliate,email:e.target.value})} className={field}/><button type="button" onClick={saveAffiliate} className="rounded-full border border-teal px-5 py-2.5 font-semibold text-teal-text">Add affiliate</button></div>}<div className="mt-6 space-y-2">{conversions.map((c)=><p key={c.id} className="rounded-lg bg-paper p-3 text-sm"><strong>{c.affiliateCode}</strong> · {c.status} · GH₵ {(c.commissionPesewas/100).toFixed(2)} commission · {c.orderReference}</p>)}</div></section>
    <section className="mt-8 rounded-[var(--radius-card)] border border-sand bg-cream p-6"><p className="eyebrow">Fulfilment</p><h2 className="mt-1 text-2xl font-semibold">Orders</h2><div className="mt-5 space-y-3">{orders.length === 0 && <p className="text-ink-muted">Paid customer orders will appear here.</p>}{orders.map((o) => <article key={o.id} className="rounded-lg border border-sand bg-paper p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{o.reference}</strong><p className="text-sm text-ink-muted">{o.buyerName} · {o.buyerPhone} · {o.fulfilment}</p></div><div className="text-right"><strong>GH₵ {(o.amountPesewas / 100).toFixed(2)}</strong><p className="text-xs text-ink-faint">You receive GH₵ {(o.businessNetPesewas / 100).toFixed(2)}</p></div></div><p className="mt-2 text-sm">{o.lines.map((l) => `${l.quantity}× ${l.name}`).join(", ")}</p><div className="mt-3 flex flex-wrap gap-2">{(["processing", "ready", "fulfilled"] as const).map((status) => <button key={status} type="button" onClick={() => advance(o, status)} className={`rounded-full border px-3 py-1 text-xs font-semibold ${o.status === status ? "border-green bg-green text-on-green" : "border-sand"}`}>{status}</button>)}</div></article>)}</div></section>
  </Container>;
}
