import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, View } from "react-native";
import { Stack, useLocalSearchParams } from "expo-router";
import { T as Text, TI as TextInput } from "@/components/typography";
import { api } from "@/lib/api";
import { useApi } from "@/lib/use-api";
import { useAuth } from "@/lib/auth";
import { useTheme } from "@/lib/theme-context";
import type { Affiliate, AffiliateConversion, AffiliateProgramme, BusinessCoupon, CommerceOrder, Listing } from "@/lib/types";
import { D, ON_GREEN, S, type Palette } from "@/theme";
import { ErrorView, Loading } from "@/ui";

interface CommerceData { business:Listing; coupons:BusinessCoupon[]; programmes:AffiliateProgramme[]; conversions:AffiliateConversion[]; orders:CommerceOrder[]; platform:BusinessCoupon[] }
const money=(n:number)=>`GH₵ ${(n/100).toFixed(2)}`;

export default function MobileCommerce(){
  const {slug}=useLocalSearchParams<{slug:string}>(); const {member}=useAuth(); const {C}=useTheme(); const s=useMemo(()=>styles(C),[C]);
  const {data,loading,error,reload}=useApi<CommerceData>(async()=>{const business=await api.business(slug);const platform=member?.role==="steward"?await api.platformPromotions().catch(()=>[]):[];const [coupons,programmes,conversions,orders]=await Promise.all([api.businessCoupons(business.id),api.affiliateProgrammes(business.id),api.affiliateConversions(business.id),api.businessOrders(business.id)]);return{business,coupons,programmes,conversions,orders,platform}},`mobile-commerce:${slug}:${member?.id}`);
  const [coupon,setCoupon]=useState<BusinessCoupon>({code:"",discountType:"percent",discountValue:10,active:true});const [programme,setProgramme]=useState<AffiliateProgramme>({name:"Store ambassadors",description:"Reward trusted partners for qualified product sales.",commissionBps:1000,cookieWindowDays:30,holdDays:14,minimumPayoutPesewas:5000,payoutMode:"mobile_money",active:true});const [affiliate,setAffiliate]=useState<Affiliate>({programmeId:"",code:"",name:"",email:"",payoutPhone:"",audienceSummary:"",status:"approved",active:true});const [platformPromo,setPlatformPromo]=useState<BusinessCoupon>({code:"",title:"",discountType:"percent",discountValue:3,active:true});const [message,setMessage]=useState("");
  const [step,setStep]=useState(0);
  if(loading)return <Loading/>;if(error||!data)return <ErrorView message={error??"Commerce unavailable"}/>;if(member?.id!==data.business.ownerId&&member?.role!=="steward")return <ErrorView message="Business owner access required"/>;
  const field=[s.field,{color:C.ink}]; const act=async(fn:()=>Promise<unknown>,ok:string)=>{try{await fn();setMessage(ok);reload()}catch(e){setMessage(e instanceof Error?e.message:"Could not save")}};
  const steps=member?.role==="steward"?["Offers","Programme","Partner","Activity","Oguaa"]:["Offers","Programme","Partner","Activity"];
  return <><Stack.Screen options={{title:"Commerce controls"}}/><ScrollView style={{backgroundColor:C.paper}} contentContainerStyle={s.page}><Text style={s.kicker}>MOBILE COMMERCE · STEP {step+1} OF {steps.length}</Text><Text style={s.title}>{data.business.title}</Text><Text style={s.lede}>Run customer offers, recruit affiliates and monitor commission from your phone.</Text><View accessibilityRole="tablist" style={s.steps}>{steps.map((label,i)=><Pressable key={label} accessibilityRole="tab" accessibilityState={{selected:step===i}} onPress={()=>setStep(i)} style={[s.step,step===i&&{backgroundColor:C.green,borderColor:C.green}]}><Text style={[s.stepText,step===i&&{color:ON_GREEN}]}>{i+1}. {label}</Text></Pressable>)}</View>{message?<Text style={s.message}>{message}</Text>:null}
    {step===0?<Card title="Business coupons" C={C}><TextInput aria-label="Coupon code" placeholder="SAVE10" placeholderTextColor={C.inkFaint} value={coupon.code} onChangeText={(v)=>setCoupon({...coupon,code:v.toUpperCase()})} style={field}/><View style={s.row}><TextInput aria-label="Discount percent" keyboardType="numeric" value={String(coupon.discountValue)} onChangeText={(v)=>setCoupon({...coupon,discountValue:Number(v)})} style={[field,s.flex]}/><TextInput aria-label="Redemption limit" keyboardType="numeric" placeholder="Limit" placeholderTextColor={C.inkFaint} onChangeText={(v)=>setCoupon({...coupon,redemptionLimit:Number(v)})} style={[field,s.flex]}/></View><Button label="Create coupon" onPress={()=>act(()=>api.saveBusinessCoupon(data.business.id,coupon),"Coupon created.")} C={C}/>{data.coupons.map(c=><View key={c.id} style={s.item}><Text style={s.strong}>{c.code} · {c.discountValue}%</Text><Pressable accessibilityRole="button" onPress={()=>act(()=>api.deleteBusinessCoupon(data.business.id,c.id!),"Coupon archived.")}><Text style={s.danger}>Archive</Text></Pressable></View>)}</Card>:null}
    {step===1?<Card title="Affiliate programme" C={C}><TextInput aria-label="Programme name" value={programme.name} onChangeText={(v)=>setProgramme({...programme,name:v})} style={field}/><View style={s.row}><TextInput aria-label="Commission percent" keyboardType="numeric" value={String(programme.commissionBps/100)} onChangeText={(v)=>setProgramme({...programme,commissionBps:Number(v)*100})} style={[field,s.flex]}/><TextInput aria-label="Hold days" keyboardType="numeric" value={String(programme.holdDays)} onChangeText={(v)=>setProgramme({...programme,holdDays:Number(v)})} style={[field,s.flex]}/></View><Button label="Save programme" onPress={()=>act(async()=>{const p=await api.saveAffiliateProgramme(data.business.id,programme);setAffiliate({...affiliate,programmeId:p.id!})},"Programme saved.")} C={C}/>{data.programmes.map(p=><Text key={p.id} style={s.note}>{p.name} · {p.commissionBps/100}% · {p.holdDays}-day hold</Text>)}</Card>:null}
    {step===2?<Card title="Add affiliate" C={C}><TextInput aria-label="Affiliate programme ID" placeholder="Select by programme ID" placeholderTextColor={C.inkFaint} value={affiliate.programmeId||data.programmes[0]?.id||""} onChangeText={(v)=>setAffiliate({...affiliate,programmeId:v})} style={field}/><TextInput aria-label="Affiliate code" placeholder="AMA10" placeholderTextColor={C.inkFaint} value={affiliate.code} onChangeText={(v)=>setAffiliate({...affiliate,code:v.toUpperCase(),programmeId:affiliate.programmeId||data.programmes[0]?.id||""})} style={field}/><TextInput aria-label="Affiliate name" placeholder="Partner name" placeholderTextColor={C.inkFaint} value={affiliate.name} onChangeText={(v)=>setAffiliate({...affiliate,name:v})} style={field}/><TextInput aria-label="Affiliate email" placeholder="partner@example.com" placeholderTextColor={C.inkFaint} value={affiliate.email} onChangeText={(v)=>setAffiliate({...affiliate,email:v})} style={field}/><Button label="Add affiliate" onPress={()=>act(()=>api.saveAffiliate(data.business.id,{...affiliate,programmeId:affiliate.programmeId||data.programmes[0]?.id||""}),"Affiliate added. Share product links with ?aff=CODE.")} C={C}/></Card>:null}
    {step===3?<Card title="Conversions & orders" C={C}>{data.conversions.length===0&&data.orders.length===0?<Text style={s.note}>New attributed sales and paid orders will appear here.</Text>:null}{data.conversions.map(c=><Text key={c.id} style={s.note}>{c.affiliateCode} · {money(c.commissionPesewas)} · {c.status}</Text>)}{data.orders.slice(0,8).map(o=><Text key={o.id} style={s.note}>{o.reference} · {money(o.amountPesewas)} · {o.status}</Text>)}</Card>:null}
    {member?.role==="steward"&&step===4?<Card title="Oguaa-funded promotion" C={C}><TextInput aria-label="Platform promotion title" placeholder="Cape Coast weekend" placeholderTextColor={C.inkFaint} value={platformPromo.title} onChangeText={(v)=>setPlatformPromo({...platformPromo,title:v})} style={field}/><TextInput aria-label="Platform promotion code" placeholder="OGUAA3" placeholderTextColor={C.inkFaint} value={platformPromo.code} onChangeText={(v)=>setPlatformPromo({...platformPromo,code:v.toUpperCase()})} style={field}/><TextInput aria-label="Platform discount percent" keyboardType="numeric" value={String(platformPromo.discountValue)} onChangeText={(v)=>setPlatformPromo({...platformPromo,discountValue:Number(v)})} style={field}/><Button label="Launch Oguaa promotion" onPress={()=>act(()=>api.savePlatformPromotion(platformPromo),"Platform promotion launched.")} C={C}/>{data.platform.filter(p=>p.ownerType==="platform").map(p=><Text key={p.id} style={s.note}>{p.code} · {p.discountValue}% · {p.redemptions??0} uses</Text>)}</Card>:null}
  </ScrollView></>;
}
function Card({title,C,children}:Readonly<{title:string;C:Palette;children:React.ReactNode}>){return <View style={{borderWidth:1,borderColor:C.sand,backgroundColor:C.cream,borderRadius:16,padding:16,gap:10,marginTop:16}}><Text style={{...D(700),fontSize:21,color:C.ink}}>{title}</Text>{children}</View>}
function Button({label,onPress,C}:Readonly<{label:string;onPress:()=>void;C:Palette}>){return <Pressable accessibilityRole="button" onPress={onPress} style={{alignItems:"center",borderRadius:999,backgroundColor:C.green,padding:12}}><Text style={{...S(700),color:ON_GREEN}}>{label}</Text></Pressable>}
const styles=(C:Palette)=>StyleSheet.create({page:{padding:18,paddingBottom:48},kicker:{...S(700),fontSize:11,letterSpacing:1.5,color:C.goldText},title:{...D(700),fontSize:32,color:C.ink,marginTop:5},lede:{...S(400),fontSize:14,lineHeight:21,color:C.inkMuted,marginTop:6},steps:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:16},step:{borderWidth:1,borderColor:C.sand,borderRadius:999,paddingHorizontal:10,paddingVertical:7},stepText:{...S(700),fontSize:11,color:C.inkMuted},message:{...S(600),color:C.tealText,marginTop:12},field:{...S(400),borderWidth:1,borderColor:C.sand,borderRadius:10,paddingHorizontal:12,paddingVertical:11,backgroundColor:C.paper},row:{flexDirection:"row",gap:8},flex:{flex:1,minWidth:0},item:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingVertical:5},strong:{...S(700),color:C.ink},danger:{...S(700),color:C.clayText},note:{...S(400),fontSize:12,lineHeight:18,color:C.inkMuted}});
