import { createBrowserRouter } from "react-router-dom";
import { RootLayout, RootError, HydrateFallback } from "./routes/root";

// Lazy, code-split routes (low-bandwidth friendly). Each page module exports
// `Component` and, where it loads data, a `loader`. HydrateFallback covers the
// first load while the initial lazy chunk + loader settle (else: blank page).
export const router = createBrowserRouter([
  {
    element: <RootLayout />,
    errorElement: <RootError />,
    HydrateFallback,
    children: [
      { index: true, lazy: () => import("./pages/Home") },
      { path: "signin", lazy: () => import("./pages/SignIn") },
      { path: "music", lazy: () => import("./pages/Music") },
      { path: "music/the-oguaa-sound", lazy: () => import("./pages/OguaaSound") },
      { path: "music/:slug", lazy: () => import("./pages/Artist") },
      { path: "memoriam", lazy: () => import("./pages/Memoriam") },
      { path: "memoriam/:slug", lazy: () => import("./pages/Memorial") },
      { path: "education", lazy: () => import("./pages/Education") },
      { path: "education/:slug", lazy: () => import("./pages/School") },
      { path: "education/:slug/manage", lazy: () => import("./pages/ManageInstitution") },
      { path: "people", lazy: () => import("./pages/People") },
      { path: "people/:slug", lazy: () => import("./pages/Person") },
      { path: "members/:slug", lazy: () => import("./pages/MemberProfile") },
      { path: "search", lazy: () => import("./pages/Search") },
      { path: "projects", lazy: () => import("./pages/Projects") },
      { path: "projects/:slug", lazy: () => import("./pages/Project") },
      { path: "business", lazy: () => import("./pages/Business") },
      { path: "business/:slug", lazy: () => import("./pages/BusinessDetail") },
      { path: "events", lazy: () => import("./pages/Events") },
      { path: "events/:slug", lazy: () => import("./pages/EventDetail") },
      { path: "festivals", lazy: () => import("./pages/Festivals") },
      { path: "festivals/:slug", lazy: () => import("./pages/FestivalDetail") },
      { path: "safety", lazy: () => import("./pages/Safety") },
      { path: "safety/report", lazy: () => import("./pages/ReportIncident") },
      { path: "safety/:slug", lazy: () => import("./pages/IncidentDetail") },
      { path: "lost-found", lazy: () => import("./pages/LostFound") },
      { path: "lost-found/new", lazy: () => import("./pages/PostLostFound") },
      { path: "lost-found/:slug", lazy: () => import("./pages/LostFoundDetail") },
      { path: "community", lazy: () => import("./pages/Community") },
      { path: "investment", lazy: () => import("./pages/Investment") },
      { path: "mentorship", lazy: () => import("./pages/Mentorship") },
      { path: "diaspora", lazy: () => import("./pages/Diaspora") },
      { path: "youth", lazy: () => import("./pages/Youth") },
      { path: "news", lazy: () => import("./pages/News") },
      { path: "news/:slug", lazy: () => import("./pages/NewsArticle") },
      { path: "heritage", lazy: () => import("./pages/Heritage") },
      { path: "culture", lazy: () => import("./pages/Culture") },
      { path: "visit", lazy: () => import("./pages/Visit") },
      { path: "submit", lazy: () => import("./pages/Submit") },
      { path: "me", lazy: () => import("./pages/Me") },
      { path: "admin", lazy: () => import("./pages/Admin") },
      { path: "admin/compose", lazy: () => import("./pages/Compose") },
      { path: "privacy", lazy: () => import("./pages/Legal") },
      { path: "terms", lazy: () => import("./pages/Legal") },
      { path: "acceptable-use", lazy: () => import("./pages/Legal") },
      { path: "safeguarding", lazy: () => import("./pages/Legal") },
    ],
  },
]);
