// Named routes used across the mobile app. Centralised so renames don't leave
// stale strings scattered through screens, and to satisfy SonarQube S1192.
export const ROUTES = {
  home: "/",
  signIn: "/signin",
  me: "/me",
  settings: "/settings",
  studio: "/studio",
  studioWork: "/studio/work",
  studioTeam: "/studio/team",
  studioGrow: "/studio/grow",
  submit: "/submit",
  write: "/write",
  alerts: "/alerts",
  notifications: "/notifications",
  diaspora: "/diaspora",
  projects: "/projects",
  festivals: "/festivals",
  institutions: "/institutions",
  lostFound: "/lost-found",
  lostFoundNew: "/lost-found/new",
  safety: "/safety",
  safetyReport: "/safety/report",
  explore: "/explore",
  news: "/news",
  music: "/music",
  oguaaSound: "/music/the-oguaa-sound",
  youth: "/youth",
  search: "/search",
  browseEvents: "/browse/events",
  browsePeople: "/browse/people",
  browseBusinesses: "/browse/business",
  browseOpportunities: "/browse/opportunity",
  browseMemories: "/browse/memory",
  browseProjects: "/browse/project",
  exploreHeritage: "/explore/heritage",
  exploreCulture: "/explore/culture",
  exploreVisit: "/explore/visit",
  legalTerms: "/legal/terms",
  legalPrivacy: "/legal/privacy",
  legalAcceptableUse: "/legal/acceptable-use",
  legalSafeguarding: "/legal/safeguarding",
  studioMoney: "/studio/money",
} as const;

// Route builders for dynamic segments — keeps route templates in one place.
export const route = {
  event: (slug: string) => `/events/${slug}`,
  festival: (slug: string) => `/festivals/${slug}`,
  person: (slug: string) => `/people/${slug}`,
  member: (slug: string) => `/members/${slug}`,
  business: (slug: string) => `/business/${slug}`,
  project: (slug: string) => `/projects/${slug}`,
  newsArticle: (slug: string) => `/news/${slug}`,
  music: (slug: string) => `/music/${slug}`,
  memoriam: (slug: string) => `/memoriam/${slug}`,
  lostFound: (slug: string) => `/lost-found/${slug}`,
  safety: (slug: string) => `/safety/${slug}`,
  institution: (slug: string) => `/institutions/${slug}`,
  institutionManage: (slug: string) => `/institutions/${slug}/manage`,
  listingEdit: (id: string) => `/listings/${id}/edit`,
} as const;
