// Editorial content seeds — verbatim from the fact-checked Cape Coast research
// (agent_plan.md §1). The dynamic data comes from the Go API; this is the static
// long-form copy the showcase pages render.

export const ABOUT_OGUAA = `Cape Coast is the English name; the soul of the place is Oguaa. The name comes from the Fante word gua — "market" — for the crab-traders' selling-ground that grew, by the sea in front of the great Castle, into a town. Commerce is not incidental here; it is the town's birth name, still alive in Kotokuraba, the "crab-hamlet" market at the city's heart. From those market roots Oguaa became, for a while, the whole Gold Coast: British capital from 1821 to 1877, cradle of the colony's lawyers, journalists and constitutionalists, and the country's oldest school town. It is a place of hard contrasts in soft light — the whitewashed Castle and its Door of No Return facing the Atlantic, the green hush of Kakum inland, the flag-bright pageantry of the Asafo and Fetu Afahye. Oguaa remembers, and Oguaa celebrates. This is where the town sees itself.`;

export const OGUAA_SOUND = `Before there was Afrobeats, before there was hiplife, there was the salt air of Oguaa carrying drums down to the water. In the 1920s and '30s the town hosted some of the Gold Coast's first dance orchestras — among them the Cape Coast Light Orchestra, the "Sugar Babies" — and from those castle-shadowed ballrooms palm-wine guitar and brass-band swing fused into the thing the world would call highlife. Listen closely and you can still hear the Asafo: every September at Fetu Afahye the companies parade from Kotokuraba with war drums and frankaa flags, turning the whole town into one percussion section.

That coastal pulse — the osode rhythm of the fishermen — is what the late C.K. Mann (born in Cape Coast, 1936) electrified into a national sound, and what Ebo Taylor of Saltpond, up the Central Region coast, carried into Afro-funk and out to crate-diggers in London, Tokyo and Los Angeles. When Taylor died on 7 February 2026 at ninety, the world called him a pioneer; on this coast he was simply one of ours.

These are the twin grandfathers of the Oguaa Sound, and a town of schools and a university keeps the pipeline flowing behind them. The Oguaa Sound opens at their feet.`;

export const HERITAGE_BLURB = `The town's silhouette is the Castle: begun in 1653 as a Swedish timber lodge called Carolusborg, taken by the British in 1664 and rebuilt in stone as the headquarters of their West African trade. Above the chapel lay light; below it lay the dungeons and the Door of No Return, the final threshold for hundreds of thousands of enslaved Africans. President Obama stood here in July 2009 and named the lesson plainly: "we can tolerate and stand by great evil even as we think that we're doing good." Inscribed on the UNESCO World Heritage List, the Castle became the launching image of Ghana's 2019 Year of Return, four hundred years after the first enslaved Africans landed in Virginia — and the diaspora now walks back through that same door. Oguaa also gave Africa one of its earliest written constitutions: the Mankessim Constitution of 1871, drawn up by the Fante Confederacy (formed at Mankessim in 1868, dissolved by the British in 1874) with a council, a judiciary, taxes, and a promise of roads and schools. We hold both stories: the pride and the wound.`;

export const CULTURE_BLURB = `Oguaa is the heartland of the Asafo — the Fante militia companies, now ceremonial brotherhoods, that broadcast their identity in two art forms: the concrete posuban shrines crowded with painted figures, and the appliqué frankaa flags that stitch proverbs and rivalries onto cloth. The town keeps seven companies. Their year turns on the Oguaa Fetu Afahye, climaxing the first Saturday of September (5 September in 2026), when the Omanhene gives thanks to the 77 gods of Oguaa and to the sea for its harvest. "Fetu" means clearing the dirt: weeks before the drums, a ban on drumming, dancing and noise falls across the town — a deliberate silence that lets the spirits lead — broken at last by the grand durbar, chiefs riding in palanquins under state umbrellas, gold flashing, the seven companies racing canoes on the Fosu Lagoon after the Omanhene casts his net three times. A chief never speaks in public; the Okyeame speaks for him. This is the soul of the Fante, stitched on cloth and poured in libation.`;

export const EDUCATION_BLURB = `Cape Coast wears one of the proudest titles in West Africa: the Citadel of Education. Within a few square miles sit the oldest and most decorated schools in Ghana, and a national university on the same hills. Mfantsipim (founded 3 April 1876 as the Wesleyan High School) is the country's oldest secondary school and marked its 150th year in 2026; Adisadel College, founded 4 January 1910 as the SPG Grammar School, took the name St. Nicholas' in 1924 and became Adisadel on its hilltop site around 1936 — hence its "Santaclausians." Wesley Girls', traced to 1836 under Harriet Wrigley and reorganised into today's school around 1954, remains a by-word for poise and excellence; St. Augustine's (1930) and Holy Child (1946) carry the Catholic line. The University of Cape Coast opened as a university college in October 1962 and attained full, independent university status on 1 October 1971. Here your secondary school is a tribe you never leave — and the rivalry, Methodist against Anglican, built excellence, not division.`;

export const YENKAE_DESCRIPTION = `Yɛnkae — Fante for "let us remember." This is the platform's permanent, dignified home for honouring members of the Oguaa community who have passed: loved ones, elders, and notable sons and daughters. In Ghanaian tradition the departed are mourned and celebrated by the whole community — family, friends, churches, Old Students, the Asafo, the associations — and Yɛnkae gives that tradition a lasting digital home. Each memorial gathers a life story, a gallery, and tributes from many hands, and rises gently each year on the day of passing so the community can remember together. The section is kept quiet by design — soft cream, a single candle of gold, generous space, and the Adinkra Nyame Nwu Na Mawu, "God will not die, therefore I will not die."`;

export const VISIT_BLURB = `Come to Oguaa for the Castle and stay for the coast. Stand at the Door of No Return, then drive thirty-three kilometres north to Kakum National Park and walk its canopy bridges — seven of them, roughly 350 metres of swaying walkway up to 40 metres above the rainforest floor, opened in 1995 and built with Conservation International and the UN Development Programme. Eat the way the town eats: Fante kenkey (dokonu) — unsalted fermented corn dough steamed in plantain leaves, softer and more sour than its Ga cousin — with fresh grilled fish, shito and ground pepper. Time your visit for the first Saturday of September and you will see Fetu Afahye at its height. The beaches, the markets, the fishing harbour and the schools on the hills do the rest.`;

export const SAMPLE_NOTICE =
  "A working preview of Oguaa — some names, faces and details are illustrative for now, holding their place until the community brings the real ones home.";
